apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
    namespace: database
type: Opaque
stringData:
  username: postgres
  password: h4ck3rsclub
  aws-access-key-id: secret
  aws-secret-access-key: secret
