apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1un9t0MotL8=,iv:q57g3YyUjBRlInY6LGDFX3G1IFYw7iDybIN1dhDrVrQ=,tag:OJAbOq6MmqHmOOTcFW7ueA==,type:str]
    password: ENC[AES256_GCM,data:h8Ady5zF7jwhazo=,iv:AALLLHBvY0OLz0HQXfYHFEbawDFNFPgpLdBSpoqHyFM=,tag:D72/zWg8fHefIzTdKRz8Fg==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:KZ0lUbyj,iv:ibUlwswgDVzgxeFbGo47UOSAh/1nZptVdsnCp7IVerY=,tag:syCFr3rTSvzo8/hFWyw9uQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:39yD5/Ev,iv:MKmOaAnc8iVRiqRuWt2nlPHLmwwBm0fnjGZlGopHls4=,tag:ubIvBU8IyqmsASd2nSWWlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOTYzTUJxWGhLRkZiVlFK
            T3FmdnpYZ0czRW51ZURuOHJnOWlJTTZUdjNJCnhNcTdvNnd0MTBjbnJ0cHVwaXlF
            ZHBYcXVGTm0vcnU5U0VNc1J0NVhxTDQKLS0tIFpJYkVXT0JCdVdHWS93cGkwTXNi
            V1F4cVhrTmRyZjhSQmhRWHFlVlFQWVEKz1WdItbd4PTmiO8oUfvPANPcOvIMmH5y
            aYHDTWoxuOVX4PMpT1TTD3yxX32upccVLnoguBu2T1RqhVXc+WFWjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T14:50:36Z"
    mac: ENC[AES256_GCM,data:dy8bNvNM6J7g4UDlm5+dJxaMsMUNUqweDl6tvmF8Nu5sQMzLlVzT6nB6j4wjHzxzaioJTR4L+JTQQpX89XC0IS63utJR95yH3uNl2B4u+UumjTNO1nSecIUxEzGTIMAAcPooMVTpNFTnsflgeqB6aY4rXvyLY9NtT44+WyX7aJw=,iv:bsWo/fdBjKpuMvyoeAqMv3SAY3N/MzrrgUeV4ltXyvY=,tag:K0BDLqxQWAtxEqVQN7WO5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
