apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ba8I3CTPmpqdh9Vxwc0=,iv:x6qpZ8/4s6ejgxj+YeR8E/A8BWuH3QN3p993oDexroQ=,tag:g0X3ezOgMrDj8cpGB2iIPw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:b6WYd0pa89DSEIeCXQcopHqEEvcCIpLFhitdsa9hKu69i0okFg==,iv:va2+x+9cY5yvGMpqJ44z2qX6FiMtfy9Z2A0cMtxnXfI=,tag:HGROoM9El48vl2uSfdf1XA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:uSHIcEhVY+KJ3PCbUPsy1jp8xoJo,iv:seOQ2FQ8MZ8AfxL4FGILo0VAaNwqixUzLWsgHhUBn/4=,tag:Bn9/jEvO36NwMdRjnifrBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T03:02:52Z"
    mac: ENC[AES256_GCM,data:3kUzEkT5AJ7pdaHWH0INbBVwAzV5r4s2s82wePuVFKTEvXAqVkG8YSwuaDXXs8EptgCoSs1WCsIdSshh3AvmvUYHRFsTclxwyUHN48iqenYuYor+e/Y4tEk0h/hPFA8VAfqkevK8W5LYkxk/rlk2APUyies9xPemKbcCJ/8foQU=,iv:2xQLOMDGQj076c62XTGpo7iMtPsFIuVAgXnb/RuhDg8=,tag:axrA6eYIDC8guI1fhHOxcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
