---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/jellyfin
              tag: 10.9.9
            env:
              PUID: 1000
              PGID: 1000
              TZ: Asia/Makassar
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${SECRET_DOMAIN}"
              JELLYFIN_CONFIG_DIR: "/media/.jellyfin"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 180
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
              readiness: *probes
    service:
      app:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: 10.10.10.106
        ports:
          http:
            port: 8096
      discovery:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: 10.10.10.107
        ports:
          udp:
            port: 7359
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: nfs
        server: "10.0.0.21"
        path: /tank/media/.jellyfin
        globalMounts:
          - path: /config
      cache:
        enabled: true
        storageClass: openebs-hostpath
        retain: true
        accessMode: ReadWriteOnce
        size: 5Gi
        nameOverride: yes
        globalMounts:
          - path: /config/cache
            readOnly: false
      video:
        type: nfs
        server: "10.0.0.21"
        path: /tank/media/video
        globalMounts:
          - path: /nas/video
      music:
        type: nfs
        server: "10.0.0.21"
        path: /tank/media/music
        globalMounts:
          - path: /nas/music
      photo:
        type: nfs
        server: "10.0.0.21"
        path: /tank/media/photo
        globalMounts:
          - path: /nas/photo
