apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: security
type: Opaque
stringData:
    server.toml: ENC[AES256_GCM,data:yVqgelM/7FAMWwlSRknd1CDUlMAAbKCyBZ7hwnoGA6G9rnTI8uZRDS4I/fg1lkjbEKJZHr0LzD0t3A0SRVf6Se0ufVgHFBveHP888t0IxUInCFssCJ5F9ffYawt97oq5tqZr4s7fmndaHKAKFRYtjUHF39wwvkCx89wWBlhOyVRnTMBzzraIN8ckV8FanWKC4ggVUqYxESwFLKCqxFS8JGcxNE7wnxWGEiAWJfE6P6Ua7O+naRNSze+EAbrHr5wr5wV7bk+Qb5I3gNuU253c1f9JtlhqJqZpvpmrkgLUdiCoH5y+pQ==,iv:T92jC9SnD/9m/h5oonGngXpkdUvPHttP9Ss8h85Erjs=,tag:MtuHlAN8VugFuQAcPKq3lw==,type:str]
    groups.toml: ENC[AES256_GCM,data:5WGhn/GWZgQWPgqjWvIR9oXicM+tsoKw6pS7jcbKN93uwEdML15hAKySHICInqnd1KyfWS+Drf38m8K+8bAbbn1wqQdQhwG35ggkodzrjrT3QlVJkpGa6atYOEl6BWxbMq5QeEDC8QzCGmKP4GB+ExFLwub5FOGzqEMZcJmj5N0N5Yni9GlvQC+aKSLOcXOWoWBKRYaIRgnc8dHAki0=,iv:5kZzFwzUZu9SMhCHw7vc0DhGSEA4XUB2hIKRLt05okc=,tag:BGghCAMVoVDn+JK1V+4rCg==,type:str]
    users.toml: ENC[AES256_GCM,data:YaqXJj2us/IeFsDzw1wCSDdfSUgpfKkcgYvSxp3gpeSc7ABQduM9HoQAG+8k+pdA5n4zSc9Mi9cy9dRuOA1EwDSCkIaz4zG/gyV7SCyR2a4dcirq+hPoAHi7y9/bsqrN2nyul16f+8p76jMMlQ9w5GwNChyexxnaY3ZeWvn0Jh1ypIayn1ynVeFt7TPXXPWfhkHNgK4X21e42I3T3FEHAg9c2o+JXSKO+j2d/g1NdmO/x2PKg9khvZQBV/YmDnE3mz/b4kBVgz3aZlhRinIZYOjHvOJjqgeQ+w5FcwrMDNm+LwBRdQ5olfLrVN5wkYt4PSXSDSu7B9P6AaKtBgy1cRbFwHx7B0OqUWKQCXSeZ2PUbjodtUed21GwhofDDBg6aULaLAWwWzl7W+a7lw6lY5PPdUeYjXNkurN1cPeirq4CYwmFUIj9X23thRTG0sbkeHqDKOgZdMf4m1xzKiROouo40jwBgXnNVGSgJODu94LP2EqR9mLBZ7kwlscRGJg1sjEUXLoSYHCUjl0Go7QETNN5TvhTORwlaQk9olzajMc4/E+xRWaLXyHdsAPd88YLQPEg3gHyDleDx4GdQLSxGk2j762SExuTD+0N0d4CZnO37nNGI7XvCODx8xvH34wa+IVYHG4INHW/+UDB2EV8rjhmkirYarfgel4yP70qQAxWpOcHxlREeIcufXNd+m0KxQzFKrO99wndGwfncgfQ4Lt1GCl8AtuSU/noS76bYHX81H+FwAsq82ArrHQaOXPwyrGavwgZUmRVZV9wfQ2kSlxZiU/7VXgK/pG9U3eADj2X31vhupTtfVhAarHKg3IP5aJSbEQN+hf94+SotyTzev04Rmvud4X0QbAL7SiC3AmogzcgI5L1bYiO0TxmLTZY60McgYfmETmFZGNjtjYIdmBXZlCFeaSImPCjvK5M/oD6dIdd60NYotLR3NyuN1HHWDgtKO9I1RXtZfRI5RzdpfXVNLaBf4x8qYrOdpUJM468udZVZymDx1iNvJnvlcoO7MZi3DjHwFrwdpnn8Sbej4QDcJIh6ZwpCEY2KenMKGtdYsNZ7tMKU6Ub6DImGDQFncqanGsVJvz6TtQbvYyxj4XhKqCPJeAJOXcun9UQvP8z1eVmmGSyb0g2jkBj+49PLJxHTkzA7DBa4EwaG6axIzN/OU8xfkxme+txwZAm722CxQUO,iv:MXipuyftym07MnaMzV4yszyqFdYpeVP3gToIrWK2dBI=,tag:hnWgAUlgcZ5HTpUWecUHpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aENQVURIdVhZWEpHNmNU
            YUg4aWEwdFYvK1kwN0NWUktuK2FKNUp3RVhrCi8rUmlzSkVaZ0ZOVG9pN1RmRERF
            Ym1Va1lFd1RxSS95Ti84UEI3K25OUzgKLS0tIHgxS3picVVxQkdFaGlSTVQxYXFK
            R3pCVU9GRkZRK0t6QlJqREhxRllkNUkKKogPb4ygIefzdeTH5Pj9ueriBdL3Gi7/
            mkxKMWltlio87ZPT7Ee6zd+2d55522bSYcQs8NZm3jXHmqWvt8moPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T11:05:24Z"
    mac: ENC[AES256_GCM,data:llwfU8tTvOfTzCcRykW27CJve1DAx7UyPmoJKYpayce02VjAKmozs6UeXLOWFOG9T77BD5GQ6bBGS1v4TDyOLhlVSyvgJYCWwkXPKtNaPeEM8+/NLlBbNKvfsZOW5LIhTIrjkp3I7tF9yqfAEGQbTZPxuVAWvzvTLCx0uqkv6OM=,iv:cVs+Z3FYWgeeeCzsfb3t1EB9e0aoci5lW2gG2S1vOEA=,tag:bV1LAHi5Rpxn6QcfrLE0SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
