apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: security
type: Opaque
stringData:
    server.toml: ENC[AES256_GCM,data:yVqgelM/7FAMWwlSRknd1CDUlMAAbKCyBZ7hwnoGA6G9rnTI8uZRDS4I/fg1lkjbEKJZHr0LzD0t3A0SRVf6Se0ufVgHFBveHP888t0IxUInCFssCJ5F9ffYawt97oq5tqZr4s7fmndaHKAKFRYtjUHF39wwvkCx89wWBlhOyVRnTMBzzraIN8ckV8FanWKC4ggVUqYxESwFLKCqxFS8JGcxNE7wnxWGEiAWJfE6P6Ua7O+naRNSze+EAbrHr5wr5wV7bk+Qb5I3gNuU253c1f9JtlhqJqZpvpmrkgLUdiCoH5y+pQ==,iv:T92jC9SnD/9m/h5oonGngXpkdUvPHttP9Ss8h85Erjs=,tag:MtuHlAN8VugFuQAcPKq3lw==,type:str]
    groups.toml: ENC[AES256_GCM,data:5WGhn/GWZgQWPgqjWvIR9oXicM+tsoKw6pS7jcbKN93uwEdML15hAKySHICInqnd1KyfWS+Drf38m8K+8bAbbn1wqQdQhwG35ggkodzrjrT3QlVJkpGa6atYOEl6BWxbMq5QeEDC8QzCGmKP4GB+ExFLwub5FOGzqEMZcJmj5N0N5Yni9GlvQC+aKSLOcXOWoWBKRYaIRgnc8dHAki0=,iv:5kZzFwzUZu9SMhCHw7vc0DhGSEA4XUB2hIKRLt05okc=,tag:BGghCAMVoVDn+JK1V+4rCg==,type:str]
    users.toml: ENC[AES256_GCM,data:Kfqtl6RY9LPt9aXtseFf3rQIrU5dbzkQ58HXgshXqv1govB6LEZS2vEpy/dFExmIWLTo/azc5r4+XjlOH0H0ZBy4yhe/hI2NBhjdS6CSFcc4IN5UcwexqULzNg6vdhFEJiJx4/Z99iVAm/hN3nxT6w14dR6xNsBMJqxoZ5Z4qezK57NlINaIR5Qi0ZU3nXa70TRtvGBP05qMujxGzeaxCc0A7Q08VYw4weoQnNPvl5x+SQyT13fWcWmT/EdNfMnntyM4ZuuyTShIAvK3Vs7r6KaHfEK6SZprEISMAcaXap4muKN11biKYQkkr0Me18XeuIO23/5nNPv/e5mOGlV4Eu3OtJhZMGR4E6Ccax82agDnwWt4EpEq0V0WSVIpjs8eaqMk5X8qixETAEiZ+IToZyB8eZfFeH1UR6YioPoWsTW2Dagthkk1sBdoAwITvZOk0BzeCAEyC11MyvRfl3Y7t8ioWtihXrIXjdHWHKXlmtgfGlmUuk3ZvEGoVIlEJb+VheHBwVvCxnG4HW3k6oPsl4i+vzgr6SdNRtsscubCHilvVdCqMfE8SM584pKbp2TKLltrpMreFxbQJ9huA4GgWXicYL1txOWo2z9k2pyRbV4c2HWA3D3GLZoIpjOQi35tCvSuIuGSIkgI72VnZpIL5Agz5qnq5D4ed0XnkLxPFkHFTkKYHkzXzLRFkWpu+piuy7OhqUS/YflXM/imzGFIR4L5hcgIbKkoPtCw72Y9R4+2NT+276gh0fA7Pl5RY7gLhjtkrBanugJs7OWbDGXU/bJFeIOs2alCgLVnupphfv8eqSQzAquhIE+1I6LDcjyIfG9Cwb7Mu3rnTCEyMy0RGDPutD8p5VokZ8UwiX+tDZKyBe/0i5z/goQexAwbAPPzhju7GFjTX+OdPqE+eDNbMOC9DlIDnJUV1BvHW//DUzs+j7gxGGGZ0s+uprNV7HP0MADrkl46tyHo0UirmHkiV95f48GBFMyV1jT5/pkP6E+nWGoLvkyzaxEaQ++UguPLSLsqo+cH+cfyXkr+gTXgY7rNu2qz7d7a66unr5CqK/27B1W+5YOnzIqfJ459v5Uevi3VeESB1YRUC9cRdPQ/TXjyxcA5s91gcPV1JKtlHzJKW19G1x0g40N5V+tsWOIHz4RmmC3l0/A7mu4ul9OShnrIkpL/iZkDYgNAlFAGFi4O3dd8,iv:FyobNVVQH5m0f3l/iy9W7aa/zeInU2Wi6scNx2lm924=,tag:rYf5i6G/wenQU6p/8UR4oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aENQVURIdVhZWEpHNmNU
            YUg4aWEwdFYvK1kwN0NWUktuK2FKNUp3RVhrCi8rUmlzSkVaZ0ZOVG9pN1RmRERF
            Ym1Va1lFd1RxSS95Ti84UEI3K25OUzgKLS0tIHgxS3picVVxQkdFaGlSTVQxYXFK
            R3pCVU9GRkZRK0t6QlJqREhxRllkNUkKKogPb4ygIefzdeTH5Pj9ueriBdL3Gi7/
            mkxKMWltlio87ZPT7Ee6zd+2d55522bSYcQs8NZm3jXHmqWvt8moPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T10:44:27Z"
    mac: ENC[AES256_GCM,data:3Myr6xp/z7wgZAtfRgppyaJTrEDQLxSfTWLnzvPd1fWSo/jl0avoRv3DH4j3pG/3wV1Z6iHbQWuJ1H9RToO+X8NWGIqMYNlj49MiIiRI7ka9HBOieh6QUrXTPxJLOS5frQ7L42qxXefmKM6VVkt/NDcmqIe9ZMFWX6NtMNb7AfM=,iv:Jhyojfl0kFikckiMso6fDLZlfvhJdyycj1hmnjFCruM=,tag:CiaY61Ua5PNhdysrkuDKMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
