---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jdownloader2
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MYJDOWNLOADER_EMAIL: "{{ .username }}"
        MYJDOWNLOADER_PASSWORD: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fed86245-7f2b-4706-a244-b1c100c261ba
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fed86245-7f2b-4706-a244-b1c100c261ba
        property: password
