apiVersion: v1
kind: Secret
metadata:
    name: telegraf-config
    namespace: database
type: Opaque
stringData:
    telegraf.conf: ENC[AES256_GCM,data:VO9wGXTG/3QfWNX0Zwb+qhYJvPqVqCCE7AWIM0Ew8Bpz/twSBuFvjvnCyGlEuS6ArTH4ssDjloKAfAo+CSAObgdItI9ri4qqiwdr+wbHnzX5pTkITQU5oH4JHizytBukfqfafwnDKUiOADSb1q+qBcc20RnY18s3ce/UwUpesaN/+nyMpfM2FRJvxpMu3mY0wIH42IPiBJnF9slsydqkfs8g5PXUbslrFxNQoeLN3QiJ1SJBUMWWB6ykfiH686uU4ipS4YLb6BK4xN7bElsvi5mi/dRMLwy2EuDOlnYZstydso7ylEHPuKfvgLfytoODkQvvfeAKyEdbg97u4nzUZa1bz9AGEaRjJEa8PmWks5oS65jhy2ThqWuAGPX7Z6kgRsmV5bzVbHb8LyyWi7Z/PaR8tfz6m3iR8EGwK0SA4TrKeCi2dOcAm8L99ZSiqvpbpEkmB5YPvrXUDAl/Ao1kwqrlinxRgeXOF0DLN6ost1Gx4rVB9RqOt45/QZ/jTHCqLiuNcu5EIaGnxEMlsuYGZQLCkngC2L46YLwjRwnmjxdDHD3IY/+9bso8uPU4NPofVzpTze9KFHXQSI4/k5RA0ISLmZwcL8sXexGjKR+WB49AHbv4GvA9gzS2jlpEcbPajiT6mqaBPwmbF4RCZR2NEXZMIMmQ7yldL61tDmd0ZkrxoVkP58eaJ+TYfzhl,iv:iLTYcFQ0KoPOX+s9kmLrWxFnEtoTbCyJwKilBhLscEE=,tag:gDGj5uuI73PhgSz2fTq49w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T10:35:07Z"
    mac: ENC[AES256_GCM,data:ZBaBgIgflgrqAlaEmuR2nSDjwFffmlFOmGtn1pmfOoZetH6xYv+SxcEFotqBwkB8knw+e08Jnxads0Vh8GvJN7T0mdMGZ6oOrDfZzbwlAfPE+qq5xhi5xVxkytNok/02EO/9OEjSFGk61G3hBt3z5d/HRwo4XSyru3gEgXVsZnY=,iv:FM0BKq/Awxg/abVhFhf1Z8l6C7BGHZdlb4Y0udAU2G0=,tag:iTQVnWXaNmTcQgF7oZYFfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
