apiVersion: v1
kind: Secret
metadata:
    name: telegraf-consumers
    namespace: database
type: Opaque
stringData:
    telegraf.conf: ENC[AES256_GCM,data:nsC6n5bMd1+maHMVKXLPchuKdBkzMq0E0bXzS4oxfgL6mJVhuSc/xducgKOIoB4Y014P7vc3aELZXQ5WLIezk3SBL37haS02q6mX6TCJkoF5//ycoBhMbZK065X9rBiN0fRnk0Ho7Y48oHVFG/NMSNwBVrAJPpr3ni+e8+XO7qWdNqHg09TV201ubvqaraZHEdQAJIryKOlu6vjuTDhWzM5wYd/8AysTNaDrWOux0yaDCo5RiC8E5cKbsHjvZagthYJ2clvvUEv/zkMYLmGdQtX1YfEuObElGiQxaRtjQpAjqktDTuj62dVPbj+xJcgsECi95LMrUlHm+YOZe539Jb6PqtKLB0QQI15EpXPG3xEJfnQ6fmwqm6UEGA0dWyCz6/XgInRYQ5yXgjwxKvzk4fSwNGZNWs4bMbImoqNyGGW8BZQ6cbJoSbjuvq2PzXDIAEZcIHKq7aeUGnwU/YY26RKIzuywL5Ka1M03lj/xmouh9RUGAcfCWBpaYEiYKOOx7Z0sDyEWYPmNZxdBRoLnWEwB6sDZQC4rFvXWi0oZDqflUOEKKChM/NAlzZ57rDPopEBvj2lnBMP6emOXtc/OF8qFzuTWdFxFk2xXhQ5a2mxnSfOUY1fupt5bLAinYl/r4J5TgCEyFOjqRQOeJGxXd17uIfjCzlRN1ja6mH9WHKW0hbPu3TspJVXfQDJOgDRljSwO8n+sNpJRqXq4KBnxd4ZyK26B3yuXfEuAr1H+FA/QuwAbPySS7RxPx+g2mGOCF1SzD7lzHdvO3KP1LBMhz67vX3OPBT/NETaNKxr45V7uSxud7owq7AHytWnNvsLbUrOInMgP3DDcW70/s8N8YZUcHbHSN7kddZbJfGFzgKFNtDhII3RFLfBFIOyUqmk8/141vbtiXib7xuVac2ds7HO9pDOIqfe/y2r1X8VlCDR2AinMKDNLIUPHXBBc/yh2ZVtbt6d9WTJMRmL4WbXChhzGNI7xtaj8KUdOeipG0/RKpQ9t92x6qlOkVKAvHx5BQUy5SJOCl4vK//6oHy5b5UjPnkti0djVCJ415egYun76MzbuRrj5W8NdV2bks02utY4hVQspLEef/JEx1pL0242N5UK7lrb4nZggJnaCX3TmlmGfGoHc/17Cn6PjCcADDHnaBH4S5SGrvMGbIRAML5ZlitrErVEDOalgWvQVEehY37WjJVnbhAcRrabQAEOOvY8pUhbANhNUvY5V3MJQ1TIY3U9Wv0ovSYiGr5uYDstjAGmwb072FF9f0HRHw2jfs2sITUSEXazUreuA5W06R9Ve39ruqNPA4KSykvy2r9hJ3Fm2VR/PpgEBMWgqQkwe/Gk=,iv:kzA3ohXQrCcxDTW+1ljMJRGhLH3u3AkQ2kDBJF4bdVI=,tag:xtlinxrZCcWoSMot5h8JNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T10:38:29Z"
    mac: ENC[AES256_GCM,data:NIYPv6KJ1LAonmq9kNvtYcSdqFwd43cCBHPXXqRXO158oyynZdgQWnvtddcC6gDFoZXp6OIJBw944C/7sZdwV+K6wF1NbtUmhHjPym4ixhgbP/CkRb84qkWVIBS21m5XuyntP/S1KvQYQNQPaorW+DWoEzVX77qsO1xUNwtiv0s=,iv:8QMDms2Ye3ivt2SLUHMfXUOO7KMmIyYDomRMDRrtZFc=,tag:RWDt2HW4ZaEPLwEtlB3a6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
