---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: common
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.0.25
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  timeout: 20m
  values:
    replicaCount: 1
    recreatePods: true
    service:
      type: LoadBalancer
      loadBalancerIP: "${SVC_MQTT_ADDR}"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - emqx
          topologyKey: "kubernetes.io/hostname"

    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_LOADED_MODULES: "emqx_mod_presence,emqx_mod_acl_internal,emqx_mod_topic_metrics"
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_rule_engine,emqx_auth_mnesia,emqx_prometheus"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_NODE_NAME: "emqx@10.0.0.104"
      EMQX_CLUSTER__DISCOVERY_STRATEGY: "static"
      EMQX_CLUSTER__STATIC__SEEDS: ['emqx@10.0.0.15','emqx@10.0.0.104']

    emqxAclConfig: >
      {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
      {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
      {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
      {allow, all}.

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    ingress:
      dashboard:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
          #nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
          #nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
        path: /
        hosts:
          - &host emqx.itstoni.com
        tls:
          - hosts:
            - *host

  valuesFrom:
    - targetPath: eqmxConfig.EMQX_NODE__COOKIE
      kind: Secret
      name: emqx-secret
      valuesKey: node_cookie
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: admin_username
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_2_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_2_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__3__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_3_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__3__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_3_password