apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: common
type: Opaque
stringData:
    EMQX_NODE_NAME: ENC[AES256_GCM,data:UC6ZjoR7u5y09iLnZsAn,iv:lS9rNOhJtwtdLuSz1USn20ycNc+n/C2QB9KNJz3CSrQ=,tag:Mqu67F+1ceSSV0DypKR6WQ==,type:str]
    EMQX_CLUSTER__DISCOVERY_STRATEGY: ENC[AES256_GCM,data:P936hJDY,iv:mmcjdCIg+Wk3sDj08un0k8QMZcoPQD/p3mZIWH4d32Q=,tag:mMBv+UOaZuplhzxHb4x+cw==,type:str]
    EMQX_CLUSTER__STATIC__SEEDS__1: ENC[AES256_GCM,data:Iybh+yLTgimrzGkyoBA=,iv:VEDhZGjLp+NC3PtmlZp5ji2XYiUcPvaP+xc/44edEQ0=,tag:k54+PQ/H05bfsSpkBSyTIg==,type:str]
    EMQX_CLUSTER__STATIC__SEEDS__2: ENC[AES256_GCM,data:7STtCGegRdCrkfGI+ijL,iv:ADzi1DzXWESvRgRbVxw8HnvgvTx4TjacrpG4gr3+cEE=,tag:otU2HDDIpoZ8YdxRlWB52A==,type:str]
    EMQX_NODE__COOKIE: ENC[AES256_GCM,data:f+Dulc2B/pU9Cc2o9qHBIChUgXhBuESjd6txhNXDZw5wksXlxSt7LhtkL/L5fmaz50e6FMvDj8aChM9utwn9Qw==,iv:ZHLtNEWHVIYMTa4aiwWXd/E+95FWAZDa70ockOqS3ug=,tag:zmS367fTcijwZXYnufxPeA==,type:str]
    EMQX_AUTH__USER__1__USERNAME: ENC[AES256_GCM,data:7V1zwA==,iv:UOY3QZaWQF8rvvm8M82zCB2HfHm8zkcWgJKTGODvgDM=,tag:1KxZav/yj8R0ojMT6gEt/A==,type:str]
    EMQX_AUTH__USER__1__PASSWORD: ENC[AES256_GCM,data:kNi0U+lwlfp29nONJ98=,iv:FiGnBCa1oNB2xudhFWUWrZ2iCZ12E+2t0qpbKnGDOmI=,tag:d4zkcnnd2toP1b1Gff9Kgg==,type:str]
    EMQX_AUTH__USER__2__USERNAME: ENC[AES256_GCM,data:zn/RUw==,iv:akx8tXnO6woTQvJaswNw4RaL7s5ia4t5LP3SkbZoq5Q=,tag:by58/czAr7TKkiIGHaBqWA==,type:str]
    EMQX_AUTH__USER__2__PASSWORD: ENC[AES256_GCM,data:8sBRIAKd4RCJVsbt2lY=,iv:jIPxeP/4smvuHkOI+uAVDIAsMkrLjgsFG9DDeSwvI9c=,tag:ADVjKP5kneizsenjCRBYiw==,type:str]
    EMQX_AUTH__USER__3__USERNAME: ENC[AES256_GCM,data:IR9fSUesLMU=,iv:reuqJPbINrINVkrnL9kPLVl/rcfnNCkfU4HqMYL+kXU=,tag:8gKqF7Y4DiXLO3ApIsuftw==,type:str]
    EMQX_AUTH__USER__3__PASSWORD: ENC[AES256_GCM,data:OmfP8D+pmDGhu5yMPLg=,iv:etxXdVeXVnZd2pDV92FbnS958XAlWMcEH+imyx5GfHI=,tag:kl54invkyjyDWRe62FU/dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOFBVWGNBNXFSTUpJWmNt
            SXpzcENqd3REVTVBSkV1RkkrZkp2dTBGNTNVCldDUWtPWC90anhpdENUV1I5cWgy
            L1ZIcVBBVXJQaWVRWERHY0h0eGlNclEKLS0tICtILzYrVlg4TjI0ZStsZ1dQQ3hW
            MkkyTWJsRG9idFFVMG9sdmRhUVdKTDgKzZ1uvLWxE8CZW6A7XbJQEMN015UIoYnh
            fS1I+Rdm5z1qfOmj6qpzoDjDMC+uAgb46KoVH7X66v27sJAEUmxCTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-26T01:50:02Z"
    mac: ENC[AES256_GCM,data:C+NPm7N1LHiz67PR4w9MZmmtM8jYljOCnBC36oo4ALsK4icDawWt4kn55urqf+T2KhycK3+D/CNCBi8clAlnGWbLpury2BX+ze5xD/gIrfZnKzPEhWqTzmTSBvidzojykKiPawPft4A9NO7irII9+vc9rj4oyhTHQuUgD4eb7ko=,iv:1o0vj01khTZWSRWnBmv0BHcWFXRMVleQDO9JYUz5axs=,tag:F6C9NlN3QaHOXESPX3ewnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
