apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: common
type: Opaque
stringData:
    node_cookie: ENC[AES256_GCM,data:0AkM04+OxIVTIMeIfOiAijIXsBZc/uGgrlZEOB/q9bENww65WJ1881Fb8O0sR586axlbDFUYpvAKd0Ao7kSrIA==,iv:02yZfBsYbSJTkXM9Wlb6VQP/povlyZac4eSVW02cbHw=,tag:y0FCRQBJfZICGgkuu8gr6g==,type:str]
    admin_username: ENC[AES256_GCM,data:PfA/SQ==,iv:7E8VDBZcPrQ547XJaUzHmBMD7HHR8OUm7PguU6yYYeM=,tag:2KaAhq6ovVWzUj4rAaH5RQ==,type:str]
    admin_password: ENC[AES256_GCM,data:oRpFJw/xgYD4Ymfq,iv:Q9+Oyt1kueVPhDhJa4/URM/hymLfuwgsxQd1+e172Ps=,tag:AOemvHCF/106Zd7J+Faidg==,type:str]
    user_1_username: ENC[AES256_GCM,data:ikXX2Q==,iv:s3yTV568Jf8jq4sbUghFCikEm5Fudfe5+QxgQdAwMBE=,tag:ApDieaUTIlBwKN0Czw+coQ==,type:str]
    user_1_password: ENC[AES256_GCM,data:WlQzjn0Fnu+6yPHFqCc=,iv:MogEQygpb79/dR6zx303EItLc38cxshm/2hFt/j78ng=,tag:MjVKoUA7giEkwZ8qrVymkA==,type:str]
    user_2_username: ENC[AES256_GCM,data:PuBDKA==,iv:bp+eBjzC60GkGyxTUAl863hdhvxc5fXKLvCBS7xAul0=,tag:UwMdSTZ1lZnScxkBTaAfOA==,type:str]
    user_2_password: ENC[AES256_GCM,data:9uBbM/Xv2vIMbR2MpTE=,iv:z/s0462LlcBvBx+LqYKvz9jz/WZ+ngmTjjs5cwplKEc=,tag:mliq1eELJMwKpyAlTncvWQ==,type:str]
    user_3_username: ENC[AES256_GCM,data:UxbSFjdo4jc=,iv:zHyzgVR1HmEAI8WG5pCAGGIKEbIDogDK3KktKRqlf4Q=,tag:p3SeIW+M1kKL0f6zUSLCcg==,type:str]
    user_3_password: ENC[AES256_GCM,data:mGaKQ6IxNdWmXRAPozQ=,iv:LwLJVp+h1lWQE6cJgUxH2xf/tWWrhNGmNeoi9AJPzWI=,tag:BA4p4nxuzMhqb+rvWxr1xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOFBVWGNBNXFSTUpJWmNt
            SXpzcENqd3REVTVBSkV1RkkrZkp2dTBGNTNVCldDUWtPWC90anhpdENUV1I5cWgy
            L1ZIcVBBVXJQaWVRWERHY0h0eGlNclEKLS0tICtILzYrVlg4TjI0ZStsZ1dQQ3hW
            MkkyTWJsRG9idFFVMG9sdmRhUVdKTDgKzZ1uvLWxE8CZW6A7XbJQEMN015UIoYnh
            fS1I+Rdm5z1qfOmj6qpzoDjDMC+uAgb46KoVH7X66v27sJAEUmxCTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T13:44:38Z"
    mac: ENC[AES256_GCM,data:aKbUIVEODJVtbHjWf4JE9xYMGV8Togo1vryTwFOAr4W9ZtCKjWD/QB7+ovm5BuTaGwEvmUDOmW/cM+lVLybXuxJb/m0uSNyHwo41FmQBQWsWQiO1TpR1u/wrRqmW1kSmjLbllhijg6KYsHkpefjLTt4okA9pkqg1VzmrE4booJ8=,iv:JDppUoCLEElcs2kztHJlHarC/FpcZGNO7aJIuj5P/Js=,tag:zXzFtmmmzxmmyweqGY6bLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
