---
- name: Installs sops
  hosts: localhost
  tasks:
    - name: Install SOPS on localhost
      ansible.builtin.include_role:
        name: community.sops.install
      vars:
        sops_install_on_localhost: true

- name: Ensure homelab converged
  gather_facts: true
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  hosts: all
  tasks:
    - name: Ensure node configured
      ansible.builtin.include_role:
        name: node
      tags: always

    - name: Ensure core role included
      ansible.builtin.include_role:
        name: core
      tags: always

    - name: Ensure storage role included
      ansible.builtin.include_role:
        name: storage
      tags: always

    - name: Ensure apps role included
      ansible.builtin.include_role:
        name: apps
      tags: always

    - name: Ensure tools role included
      ansible.builtin.include_role:
        name: tools
      tags: always
