---
- name: Ensure homelab converged
  gather_facts: true
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  hosts: all
  tasks:
    - name: Ensure core role included
      ansible.builtin.include_role:
        name: core
      tags: always
    - name: Ensure storage role included
      ansible.builtin.include_role:
        name: storage
      tags: always
