version: 3

vars:
  PLAYBOOK: "ansible-playbook"
  INVENTORY: "inventory/hosts.ini"
  ANSIBLE: "{{.USER_WORKING_DIR}}/.venv/bin/ansible"

tasks:
  deps:
    desc: Install homelab dependencies
    cmds:
      - pass hl/age-key > age.key
      - pip install -r requirements.txt
      - ansible-galaxy install -f -r ./roles/requirements.yml

  play:
    desc: Start converging homelab
    cmd: "{{.PLAYBOOK}} -i {{.INVENTORY}} {{.playbook}}{{.host}}{{.tags}}{{.skip}}{{.check}}{{.args}}"
    vars:
      host: "{{if .host}} -l {{.host}}{{end}}"
      check: "{{if .check}} --check{{end}}"
      tags: "{{if .tags}} --tags {{.tags}}{{end}}"
      args: "{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}"
      skip: "{{if .skip}} --skip-tags {{.skip}}{{end}}"
      playbook: main.yml

  check:
    desc: Check playbook
    cmds:
      - task: play
        vars:
          check: 1
          playbook: main.yml

  ping:
    desc: Ping all available hosts
    cmds:
      - "{{.ANSIBLE}} -i {{.INVENTORY}} --one-line -m ping all"

  converge:
    cmd: molecule converge
