---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: dev
  url: "https://github.com/kilip/olympus"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
