kind: ENC[AES256_GCM,data:Cl3K15cm,iv:uWDQIDP43D8noME/Id3pQFpPxfPcub43gqpaI6TJd+s=,tag:K+/2B/1F1K16WoH/RaMccg==,type:str]
ansible_host: ENC[AES256_GCM,data:+soB+FL5KP0Q,iv:DNinAQ/037BqNSs9ya1uA4m20zHmnvtlFCcszUQ4f9I=,tag:52oxnbHRQXMTXI+WtMVqMQ==,type:str]
inet_device: ENC[AES256_GCM,data:JyeYTiem,iv:ZP4Wbhcxj6Arl+ted34ljOMFPL23NtFcPyfNaKFvkyk=,tag:cl2m9uW3tWTaEOh9sQVecg==,type:str]
install_ntp: ENC[AES256_GCM,data:XN2jsA==,iv:wqggmONfS4UgMvwnIv2yIdMQfWE5HAUXFXDlwf7b8v8=,tag:+Q5AshaQmFsQo/O3ynorRw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSjdsa2twYjNUdVRnSGIz
            ZDBKMy9pbnBSSjF3YXd4ZmhndS81NTl4alNvCjlZRk9wazByVHg2dUZDeUZtL2hy
            elFqL3MrSkFTMmN4YTJaTHBRRVVXTDAKLS0tIHp0SFZDU3JyelpOcTRyM2JJNVZz
            SHFkZmhYVS8va1BvQkRaZXBUelR5TWsKOlzNQxihXkgJrG9ztte0Cl2rwY/zMjEl
            /zhU2IG4LJdACWWbBTBeXvAyzJ2OTm8baAGyBJiYtu+moe/BjQiSWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-29T03:31:29Z"
    mac: ENC[AES256_GCM,data:RMnKQ1JzA/Pj6AkXy8BLJMcrPgMAxNEEhP0g2BkO72pK7e8JTooINwBSLiercgwVt/j2P8cMjyDpWTtfSR0eRp1T41g2hcGSGNEyOBdJwH8ZiGlrDQaFBBw8ZK2/2e0cBt780CHn/NyeA3KuYUXidxjuhy3/X+lPOGF0AfpZrR8=,iv:P90S20p7ezVkCSjlVro0AGdDEbFUAfsRGkijSf0em9Q=,tag:MJTK8C4kJ/UPZofy3Dc2Xg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
