kind: ENC[AES256_GCM,data:QEnnuKp3,iv:h1xuOI2c3QUKju6IaWdJA4dXdo1nHZGfCCaD9KlCKJU=,tag:NuXHzGc/gDU6zhC/C7dUWw==,type:str]
ansible_host: ENC[AES256_GCM,data:elqmvU4Fo+AH,iv:bZ9Kx0LH5+obokUt5uASrEtkeLm+MHFkrriSmrd6HU4=,tag:SGiYgwjlwq7JuOLnTgKfSQ==,type:str]
inet_device: ENC[AES256_GCM,data:r0e+NGXj,iv:q2y5mc5odrbBaboHdXdIohoA9iDnJeApNzK1xFk2Ke0=,tag:igzRv3w8Tdkr+6wi8fr+ig==,type:str]
#ENC[AES256_GCM,data:rORf/WYZ2Ih/Mg==,iv:/OE9Qj+PoXOqT7cwyHZXnn3gWMynoFfQvxjSn7TwByM=,tag:QUqUB0qOgSN7jGCxAVloWA==,type:comment]
#ENC[AES256_GCM,data:9BgHP4kZwnnVeQyRCOvqOw==,iv:e/4AxYN98cxNjrw6CE5pE8wFYSVvqzYln+/Df/j1IV8=,tag:c6UiVzkCHpdVkY8rkU617g==,type:comment]
#ENC[AES256_GCM,data:DOaX07gNeb9zaQw67qDL9d2QGjZYI4k=,iv:AgSbZtMsMRFfogMMwV/jOMOzWVxiBg6OiLd7p6xIFs0=,tag:65ofvPJgDFCrKmlQQ8Bd9g==,type:comment]
#ENC[AES256_GCM,data:pRd5J3s/TJoLntV7bp4=,iv:Z1FtHvbw7p2Ran6YAoQ/vvb/Do0m8EDyslFoztZU4tU=,tag:lz5L+613S1DUIj5CUVBXAg==,type:comment]
#ENC[AES256_GCM,data:Rp33lChy9ioQ1kYHLBFzsRVWf/qgG6naQ1PKifelFwbdFZ815arNyiqaXZM=,iv:trRu2gd9RISL7WGEDL0wDsCpU5zs7U9TQxo4sBTHoYY=,tag:geDrzyyUYFQowoMAnVuMUw==,type:comment]
#ENC[AES256_GCM,data:nhxIWyhDd6DhuPRHJ+783Jroskc=,iv:4YG+jSy1TqtNT9Nl90RRpWxYY7lILSCro6UutI95TCI=,tag:zxBsFtrEE97Q8joP3t2SRQ==,type:comment]
#ENC[AES256_GCM,data:llOvtQ==,iv:QuQYOlO4gecxcYAcfIgiUPb2CqVGzmHQbqPw6GbUErc=,tag:Htjx37dRxfSOUnC3XojkAQ==,type:comment]
#ENC[AES256_GCM,data:Qaa4jjVfCP7kr4wES6WPTyhF,iv:Vg7jSsHyhh9zO+/XtNtzGXX1h073LphNzrv0fVKmJAE=,tag:NtItrEOGNihGlMRl8yMzOA==,type:comment]
#ENC[AES256_GCM,data:PZXg7Q6ieVg6w9YMM1eb/Q==,iv:WWaV59Q16UWBjIHt+vuQAGb/0QCxaQhKLbknMvT9cbk=,tag:HfYRFCDwjLLnGTF9WLbNxg==,type:comment]
#ENC[AES256_GCM,data:zFeOA8fJMZhT0jvi,iv:J2swTHwDsQjhwJ87PMvUjXAzI5O3eZRfJShtRuFP7OA=,tag:ei9aSrJCBttN12EiC2QHww==,type:comment]
#ENC[AES256_GCM,data:CCxkFZeDUclGbL0ANkOVBBcobHYnawrkIZ5cUdKDQfWP/JehCMiPwWpO0iB33Xflm4NUsPqYdr+3NpbFVdVAAR1iZyP7+0FCzP4=,iv:+3sudLhl2YLoDZ65CKYrSy9e1GRp5uyVpAG0vW7TyP4=,tag:siCk9xiC8iTkr2NeAZYttA==,type:comment]
#ENC[AES256_GCM,data:ptCGPtXFWTLPKr6NpCaLCGOPkEaZk/L0ZGlBfKw66ix8TVUditfcR1P45P8bfg8/Z935WDQPNi3fl4WEZ6UiAFThiaIjNguIYYA=,iv:DXEnuvqPO26lBAv/hFPP2woTKTtjhZqjWDikw9EJpEg=,tag:Xmaj4FB/ygLBD1Ly+8HTAQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmJnNUE3NnZFMkk0c2oy
            eTJwSlBieXZTKzRxTkNHU1NKRklyem53TERzClgwbS9aRWdGdnYwOUQ2djNDaUhG
            Mk5kUEJUTkdwTm9kTnd6S0FYME0yNTgKLS0tIDhmT25idXdzV29tdENBNFhhOTNI
            WDJPZnRtSjZEeUs4aCtLTnZNeTJoaFkKIY6zZPMhJH94SSd1EfQ+f9qEYyU0gwNe
            2nKEUARtpQVnG7FJrs0oNycH/TKICicu3R4MiHk6a123Zljhg+QWGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T12:05:41Z"
    mac: ENC[AES256_GCM,data:RHgqUWASIlxAlZ8SrZJeaMVQi1ZZhcpB6JuYT8bRdit6OquNYH6B1+8WEeuXM3YOK2NrLZosqwHOZTD8PO9225fEiYaTyA6K4Va9VEriqpIZWvhVcxWE6bb/445y6TqDMzYV0OGoOeKCcgtG3/f8V6S8BolKZHvs7tGZOIePKWw=,iv:kxcyl0KsFnuLm5IiTP8aLm1nZcmQl1cH1FMK3TDmOMg=,tag:iVySuZArq7KeD5XMhvW7vg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
