kind: ENC[AES256_GCM,data:QEnnuKp3,iv:h1xuOI2c3QUKju6IaWdJA4dXdo1nHZGfCCaD9KlCKJU=,tag:NuXHzGc/gDU6zhC/C7dUWw==,type:str]
ansible_host: ENC[AES256_GCM,data:iUzq3QAtGNQ=,iv:igqsaw8jUIEv6sJ3J+hFdef47XroF4YGO6UsiFvpqw4=,tag:KiQPJBbqDz0t3OU3w6fTpA==,type:str]
inet_device: ENC[AES256_GCM,data:WPTnQg==,iv:Bb2/q/CD8mWGEa0LM9C3/32Bo1DZXym6F3ilCtqsTGE=,tag:rXsz+Ox9BMhoGPqqId3tKQ==,type:str]
nfs_exports:
    - ENC[AES256_GCM,data:9S3qjlv7a1EWigw7ijDiD5Y3KxqAp4z6TQIWG1/hVcj8wnUaIWT1d3WeTVJAEX8quid3gMLdpby/SKBXoTdZjzTMiaU=,iv:ww5u0hu/tzBvdxZtdDkRNOyeHZbP8/neNAnC+4XK/qo=,tag:4O12scZou5wwbskJTmofNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmJnNUE3NnZFMkk0c2oy
            eTJwSlBieXZTKzRxTkNHU1NKRklyem53TERzClgwbS9aRWdGdnYwOUQ2djNDaUhG
            Mk5kUEJUTkdwTm9kTnd6S0FYME0yNTgKLS0tIDhmT25idXdzV29tdENBNFhhOTNI
            WDJPZnRtSjZEeUs4aCtLTnZNeTJoaFkKIY6zZPMhJH94SSd1EfQ+f9qEYyU0gwNe
            2nKEUARtpQVnG7FJrs0oNycH/TKICicu3R4MiHk6a123Zljhg+QWGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T05:29:27Z"
    mac: ENC[AES256_GCM,data:gHA1QJaJCfhd+D/ovVwqOorbJsRGjaiBbSX4JCg3dGPcz3C7s+m4/WZ4hQsK64UUH1YCzwM9Ny3sLmMLrUBp/gyYTBZGehFvdUF1yHiBqX+XM/zU+h0XmPI2Lwjqllab8auZzCk4Xv+MiSRomufciCMTRpIPY8XFKFxCkmSilOU=,iv:QDImp6pgzqMzAffueXhHgKKYmfyamwXOKm2imUVfY5U=,tag:nnQaab1ruD8Tz4FrCpSBOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
