apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:cC9aG2MjHA43UmDOZjA=,iv:gr3T1q+gjE/Tw1Ar3Mz7K09ua+HmlAVI8QIMhWuhuhM=,tag:EVLccet0Ox3nmmgWDXtdfg==,type:str]
    username: ENC[AES256_GCM,data:5gPR3Q==,iv:/RUMSsXBIom4ztWuUdkC7fjMvUEIdrCJmV2gqhnp97Q=,tag:dQJWol750wn98orTli8kQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qkt8anezrv89yj8clxg5mhsgps8ygvsndjsn763p7t77eyx3uufs8turrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQkRxTUdUbWs5alp3am9E
            dTBMbXBhSTEzZVpQc25xcC9oMWIvYW1tWm5jClBJQ1Zrdkh2WXM2Y3pUWjBOTnpq
            eksrQTNRaWtZQ3JaTm5YOThReU1lT28KLS0tIHZZZWRSaDVvQkQwUjFiMmhXTkFx
            eGI2VjduNnNYNVgxNmExa0w5YTVQVGsKBIOVPLHFr9+S7FxcFeS2V6Dizw2dESe5
            UaxhU0a3NB18IUipxgd9bfSWAo4vVuD40I2mMGnXS4SBpytyPLbgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T09:22:43Z"
    mac: ENC[AES256_GCM,data:pItzdoaxjvmXzpDYhYpQWiRQWZxM5AhLlOLGV/BDWfCTZX9CqiGGtlHNFD/5MvrNTqJxzjebeidzvAp+uGi47rzL3YsHq8G3lYv7wxxL4cfkJk8ldBtypemN1/zxY6LIic84AGbsNvMH2ZvjsvSSFrkrVMWgJDhGpcya6+URZL8=,iv:B/7WqJSPDGWy0KK6gs6XylQ/zQPaBm3uBHqQp/4YlS8=,tag:45dxr87SY1iIP0JWD+2W7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
