hera
eros

[docker]
hera
eros

[squid]
hera

[tunnel]
hera

[traefik]
hera

[postgres]
hera

[mosquitto]
hera

[hass]
hera

[portainer]
hera

[authelia]
;hera

[redis]
hera

[authentik]
;hera

[duplicati]
;hera

[minio]
;hera

[semaphore]
hera

[newrelic]
;hera

[trilium]
;hera

[zabbix]
;hera

[librenms]
;hera

[homarr]
;hera

[mysql]
;hera