hera
mars
;iris
eros
zeus
io

[master]
hera

[worker]
mars
;iris

[kubernetes:children]
master
worker

[backup]
eros

[proxy]
eros

[laptops]
hera
eros

[servers:children]
kubernetes
proxy

[emqx]
hera
mars
eros

[wakeonlan]
zeus
hera
mars
eros

[prometheus]
zeus
io
