hera
mars
;iris
eros
zeus
io

[master]
hera

[worker]
mars
;iris

[kubernetes:children]
master
worker

[backup]
eros

[proxy]
eros

[laptops]
hera
;iris
eros

[servers:children]
kubernetes
proxy

[emqx]
hera
mars
;iris
eros

[wakeonlan]
kubernetes
proxy
zeus
