apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:P4ZXf1GejzR2D9GW3RhHazr2ORj32T6jpem4A5mRZ1Bo6RCXglCyjg==,iv:5gFn9sdQuhK4rSFYuxedzR3V9prquLGVNJaInrzYRok=,tag:vdfUz+NybTil3t++c9qvkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qkt8anezrv89yj8clxg5mhsgps8ygvsndjsn763p7t77eyx3uufs8turrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaTRWenkxR29ad01oT3Nk
            RjhSNzFYM3lnc1p4djRLK1daVGVONDdJODJvCmF1bHhtK0hhNmRoczl6TlIrQWZU
            enVma2t0ZiszTlkyczZPdTNwU0QyTlkKLS0tIElyQUpoMjBURVdXQlc1cStGY1No
            UU5wNnZlb3pncVVMSHl1MHZxa0lGaVkKZRhTTpQFO0HR6O7oE7SIVjlRgoNrQt/s
            HMDHAC1EZQ1ZSQhWlBKhIvL369YsGuZWPEvSOVkfjatLM8rikPjdgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T02:25:44Z"
    mac: ENC[AES256_GCM,data:sfcFi4EXTSKkBLRlHEqiprImj5WVRCzr5VKTTSRnTUYmnUCLydlOZIW5gnMnknzaseg1bmhfSwJWw29THyp+igKhaNTnUrE0jGhomH3O5OlhZl63JBkiDG7lGm/rYWdF1UpmGPNVrb/rx3y65Zjv7ORA2aZHdj4V07PpAQXwELM=,iv:OcuXUFUFJnYCFEh1+y+nWcP39N5Krlxixth5a6YtvJs=,tag:YFA4rLLfvwWjo/ygs0IyKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
