---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 3.5.12
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql.database.svc.cluster.local
      existingSecret:
        enabled: true
        secretName: *name
        usernameKey: POSTGRES_USER
        passwordKey: POStGRES_PASS
    cronjob:
      enabled: true

    nextcloud:
      host: &host "cloud.${SECRET_DOMAIN}"
      extraEnv:
        - name: REDIS_HOST
          value: redis.common.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
      existingSecret:
        enabled: true
        secretName: *name
        usernameKey: ADMIN_USER
        passwordKey: ADMIN_PASS
        smtpUsernameKey: SMTP_USER
        smtpPasswordKey: SMTP_PASSWORD
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-initdb:14.6
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgresql.database.svc.cluster.local
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_SUPER_PASS
              valueFrom: "${POSTGRES_SUPER_PASS}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: POSTGRES_PASS

    ingress:
      enabled: true
      className: nginx
      annotations:
        hajimari.io/icon: mdi:nextcloud
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      existingClaim: nextcloud-config-v1
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data-v1

    metrics:
      enabled: true
