---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true

    nextcloud:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/haraldkoch/postgres-init:16.3@sha256:029f24fb1895d03dd80a25a78fa9718521be7c6315980aa305e9ec07f6ccbf67
          envFrom:
            - secretRef:
                name: nextcloud
      datadir: /var/www/data
      #extraEnv:
      #  - name: REDIS_HOST
      #    value: dragonfly.database.svc.cluster.local.
      #  - name: REDIS_HOST_PORT
      #    value: "6379"
      existingSecret:
        enabled: true
        secretName: *app
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
      host: &host cloud.${SECRET_DOMAIN}

      mail:
        enabled: true
        fromAddress: admin
        domain: itstoni.com
        smtp:
          host: smtp.gmail.com
          port: 465
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
        runAsNonRoot: true
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.69.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          ); ?>
        user.config.php: |-
          <?php
          $CONFIG = array (
            'default_language' => 'en',
            'default_locale' => 'en_US',
            'default_phone_region' => 'ID',
            'default_timezone' => 'Asia/Makassar',
            'maintenance_window_start' => 1,
          );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
      extraVolumes:
        - name: media
          nfs:
            server: "10.0.0.21"
            path: "/tank/media"
            readOnly: false

      extraVolumeMounts:
        - name: media
          mountPath: "/media"

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres16-rw.database.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS

    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hajimari.io/icon: mdi:dropbox
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;

          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: "/"
      pathType: "Prefix"
      #tls:
      #  - hosts:
      #      host: *host
      # this seems to be required for nextcloud initialization which takes a long time

    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    persistence:
      enabled: true
      existingClaim: nextcloud-config-v1
      nextcloudData:
        enabled: true
        existingClaim: nextcloud
