apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: default
stringData:
    nextcloud-username: ENC[AES256_GCM,data:Sjmx0Q==,iv:NoYvhXBonpFxnQ0ibHx7KCvNDRFzOe90ouXZGoL25CQ=,tag:yXWas5A7d8wZiTRwQJHNMw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:HcmNEHrqO8vjtGVG,iv:5HQNRyYJUzaiq6ITQYxsHd1HNhGieOb2Jt1nfvHZC/Y=,tag:a++lR3Sbr+8hIldb3yPqeg==,type:str]
    database-username: ENC[AES256_GCM,data:dT3yUUehTxaD,iv:7BZO9K5yET0XQK/yjuAuIacn7IR3eYxFIZALkiPoCyc=,tag:FqM8qTogR7hOIpSn+K55jg==,type:str]
    database-password: ENC[AES256_GCM,data:zweMfId35sCeB2Y=,iv:zhkIF9lhjJFqVkp2kEIHrVltEJuqJs4d53WvQfeaVaw=,tag:2DcUyBaai/qm4H9dXLX+hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3QvOUNXRGRMVDJTRUVV
            VHZkdWJOS3h3bU80dVRTQW9hdVlBUXgzWHpRClhuRDJOSWs2dTdmNFUxa1pWcFBk
            QmNSdEUzTmRJY3p0ZHU1NDdsbitlSjQKLS0tIDhVQzJFUFFhWUhmb3F1czArUUFs
            Wm1UQWNNd0Y0VWRoR255ZC9YSjJNd3MKKZIHXcFGibu0sP1R3aYl1HHdk+LNK1Ae
            2PCnOj2wvzhu8eFfFCWIS10r+IySpBam1hRgXGu4sT6M4JMEY4pPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T01:14:42Z"
    mac: ENC[AES256_GCM,data:cLteI26wPXZqFXDtetea/AuutsVKl1T1Wui4Ra43FA/dG07yn/Qgf3wvZ3flSrNh84bgPzzSPCZxbiEtKd54sV20tMS5dDNYj77zK564gIxGA48xbK+t8Q+i3iyWrVmCIifQ+vUlSPYpiozmCp/zkBfgytnxDCEnlb3i+/NBzdE=,iv:yfzKz7uVwgJrpVERVf2r9NLBoRIbtffSVHHD3E6PWcE=,tag:EOzANtA5v6TPpXILRHoICA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
