apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: default
stringData:
    nextcloud-username: ENC[AES256_GCM,data:Sjmx0Q==,iv:NoYvhXBonpFxnQ0ibHx7KCvNDRFzOe90ouXZGoL25CQ=,tag:yXWas5A7d8wZiTRwQJHNMw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:HcmNEHrqO8vjtGVG,iv:5HQNRyYJUzaiq6ITQYxsHd1HNhGieOb2Jt1nfvHZC/Y=,tag:a++lR3Sbr+8hIldb3yPqeg==,type:str]
    database-username: ENC[AES256_GCM,data:dT3yUUehTxaD,iv:7BZO9K5yET0XQK/yjuAuIacn7IR3eYxFIZALkiPoCyc=,tag:FqM8qTogR7hOIpSn+K55jg==,type:str]
    database-password: ENC[AES256_GCM,data:zweMfId35sCeB2Y=,iv:zhkIF9lhjJFqVkp2kEIHrVltEJuqJs4d53WvQfeaVaw=,tag:2DcUyBaai/qm4H9dXLX+hw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ilJk8bvrOOBh,iv:lVbnEhvIx9e49XSvPOpj3OqX3m38Wo39V89d0xt+njI=,tag:+ysu0WCKioW1xaXU7fka8w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ssp9Vv55nuuysQQ=,iv:yxqc++XLqIZlwaUicyn9bNxSKeDejWXvLK3WGcuyQRI=,tag:Uzxjaalr5zT1LWZcdaW0/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3QvOUNXRGRMVDJTRUVV
            VHZkdWJOS3h3bU80dVRTQW9hdVlBUXgzWHpRClhuRDJOSWs2dTdmNFUxa1pWcFBk
            QmNSdEUzTmRJY3p0ZHU1NDdsbitlSjQKLS0tIDhVQzJFUFFhWUhmb3F1czArUUFs
            Wm1UQWNNd0Y0VWRoR255ZC9YSjJNd3MKKZIHXcFGibu0sP1R3aYl1HHdk+LNK1Ae
            2PCnOj2wvzhu8eFfFCWIS10r+IySpBam1hRgXGu4sT6M4JMEY4pPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T00:55:30Z"
    mac: ENC[AES256_GCM,data:Rjbz8pXQbOE9BG7w8r+COeBnkKJPxs+D4/5AfVyshkxi1R4isRj2sPrd1ZK8nhSblQpK3w3jR3XTDj0xPyO+pZBRZEuEP3+g2yWYG/23NhEYcV+JjAY8i8agXVo65qO4h4vSSR35GP18JwfN2PoNYCiOpXz4CaPDZwRTd2XFrdY=,iv:VTtvoP7qYj7t4hYyZ16VzJLieDmnVW14CXuGj+ZXceM=,tag:vv9n6ihuiRZT6W9y0yb5HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
