---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        nextcloud-username: "{{ .username }}"
        nextcloud-password: "{{ .password }}"
        smtp-username: "{{ .smtp_username }}"
        smtp-password: "{{ .smtp_password }}"
        smtp-host: smtp.gmail.com
        INIT_POSTGRES_USER: "{{ .postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .postgres_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: nextcloud
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b3d7e3e8-93d5-410e-b5dc-b1c000c9d53a
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b3d7e3e8-93d5-410e-b5dc-b1c000c9d53a
        property: password
    - secretKey: smtp_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7b965427-0fda-4c7e-b8e2-b1c100e5ef19
        property: username
    - secretKey: smtp_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7b965427-0fda-4c7e-b8e2-b1c100e5ef19
        property: password
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 67a1816b-6bd6-42d7-a0ef-b1c100e6a0a8
        property: username
    - secretKey: postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 67a1816b-6bd6-42d7-a0ef-b1c100e6a0a8
        property: password
    - secretKey: postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 96626829-03ce-43e5-8787-b1ba0120cbe6
        property: password
