apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    tunnel: ENC[AES256_GCM,data:OEUhv15BV/qcyfEp5jXtalh0VuGwDjSg7U8h2xgmB1LQo8fEwMQScbwxuVOiTnBfVqmPbI3sy1Udz2g+PnBIeumCloT7qqW0exq0G0rjevdPY9KzO8PE3Q7vebO7f4F8jrfjEuOGohaFRcKx9CoyjRRTF6N4uLeIKpo3rloNWQjYuZz+PiXAqvFw3A3eXikIVMBX3CKpBBLZYkLTIUfneVA4g4ft,iv:1/ZxuqpofOO/mcmwaQ0diAUOxgRq5LeWJkMil4ZiUDg=,tag:Til2vUQWRV2bEj9YT5kz5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEtEYzVhODdxdDhSRTFN
            WXE3UWx1eUpnbHdZb25td0c4emtBSisrZ1U4Ci9nUjNyeitjZE1rUWNPRTVJZUJt
            dmhlQXRoK1BXZmo2cDF1OFIzMHd6ZkkKLS0tIEI2RTdrREY1cUpTajNBckwrQ3hv
            cXRuRE03aFMrM2ZBQVVPRDRXUHZPazAKVcttirwYIW20XGipuRqdwZlsKI9fyCNs
            JXDLN34K8boXH3rt4mV/quhsIT0oRugqf0tuze8g7FmzasijV1/TWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T06:52:05Z"
    mac: ENC[AES256_GCM,data:S3pKYn9LhuGr2/XmDU2cpeE+QPOi9ks79nsfhpz7rlKLM+BZUgw7LRnpAYLuNsW0nOcqhmv6K/wxsp+ho56pC2aCrKs6azH3a0nxjtn0fEFKK3zprkibktQ5Ud9Tcx6Z4FpF3c8xuyTPu1k93lmrvGrs2xhPJhHX5aKKlMXFLbs=,iv:drxl9MYwN770xJ5kerZ/yEikWMHOe8vJSWSuLEP2Sa4=,tag:j1rkQEgMHA59sDQzYsWxnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
