apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: networking
stringData:
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:dXLmmrVqmbKHieuG0pOSHg==,iv:flb9xkE0BwFyQJ1ePFpqDOny/sYr5AFVz2YCdqJm8AA=,tag:aZfMwv1xgA0ZQUaV9d47TA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ipcLJeSeB2tgITVo+hT63P0uvPLuneFCXF9+ZGRqKMtTZY2u,iv:ka3DLXInEsx3CmClzxGjEPuoQPoM7Z7Ige8EgpLXJe0=,tag:4DgWud/F9FJBMat33rBYKg==,type:str]
    tunnel.json: ENC[AES256_GCM,data:57uizr+OJ1VtS7xwj7ERhvKEYlraJMMFAi7xztK1ThSp576r2unRRMqGpCEavxIATN8SZ8vgesv4xmfeb/ySAGfHAmBWQ9jnxp5IpqSortXNLeSC26Rk9baLGpW93ekupYf3SBliWBfTZlkFd2btjZ/QOYuXBhH9yQbF5ma60mnv2mUajH7slIFtLuPA56Cn0GOtCNKmwnluvXsSoYYhy/ol62TwkLp/3JwjZwtNUg0=,iv:WAhdh274uJhFDyoKyGJtc2nD7X5wt/Hm4jlGc4Hz5ig=,tag:10SwtgPZ8ZbayDtl3g8yJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T00:32:41Z"
    mac: ENC[AES256_GCM,data:erYVZzgGKp7NWhsjytum1KpX8Fjzo4KMLwCfq8xQM2yyGXJYQ8HQSpwAm7gly8EUy2e1Z6ubwtHlJCluT8yqRAcU8SLJi0TTIRHbeGhadb00CmMjOvlWwVnRqFD7mHRJRKVFOC9hBtwl8golCvX0rXByMh1H38bOSGnT4QGTFEQ=,iv:iHI83U0nRNU9ShHIiTFhKNJ39HzsZMV8vRS3it5+9yU=,tag:GiVfiYf8RKZvE1aCvVhXew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
