apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vq3WDe9CWyYJrqLn3eS61okU0N5QS1Nj8SskXBX44hXVmmbS,iv:JGDy7Uo6MGmmEBqBfz0UZt9uOD89yK+7roF7D4DHgqA=,tag:ES8Y4SMiXHND4GwAaGLy2A==,type:str]
    tunnel.json: ENC[AES256_GCM,data:e579mempNEEtrUEQRv3edRsXd3Zz7fMf2yJlpSq2zJyiwUPQNlz69+FB32vMAe5WespWdGH0hj+EfMkp/G5f01oyM3JB+ODG/j2zyaf3h7lbVxdzVmR0fQDX/HOJC0exGOHZbGHImmnDdXFhm+coBgdR3Zzxf1Rh/fmoTGjpjmYCOA0I90iSLSGxdLKJX468rJl94SWphH8tPnTiS7hgD4PBBfxCz4LICUEh2IfxYAU=,iv:ngQfg5BjgGegRnx0lxE7B1ofXmYCIftkqiOUxNK9S5k=,tag:gdQzH5r6keqajdxZGS/k6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T10:16:06Z"
    mac: ENC[AES256_GCM,data:5Tb12GCgLx5QUsLisur8vcoSWYW3hcZhkcqChKFp+iQ5h/KCoYQKp/HXuTxWZYQYfdbwwMyxyl0gFDofq7FI1pe6w9ZU/eQBZzil228gl/PKTQxa2s9zOu9dZyegV0ePmmG7Gm5piFBfiqTEai9mdXfgxWAI8gm7YwtqgfsfszI=,iv:oromBy37Ajc8YX3vUlKdCs+xsrPCpM1Wk0E32Oy2TZM=,tag:20V22bi3c4YV4x85UiV0XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
