apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vq3WDe9CWyYJrqLn3eS61okU0N5QS1Nj8SskXBX44hXVmmbS,iv:JGDy7Uo6MGmmEBqBfz0UZt9uOD89yK+7roF7D4DHgqA=,tag:ES8Y4SMiXHND4GwAaGLy2A==,type:str]
    tunnel.json: ENC[AES256_GCM,data:kylim9KwCRA5fYoptXqM2jUS3HHeEzzWHp65o7FaS++FnQrWs3F98xinrQryoTVSgxDXUCDO+661XCRdy32/Huxg9KB/74jGRxhSBQ6SzPXvBnSvNvtBTESqdRw0pSUl/LicC6PVJ+BWHVT8KeBDUilmw4eIelo8NYcuOhiU5Kob7YPhlee/XtueTTI1xaGRNaVfzEKWyyZvuLv14zRDeIhlFsiX+hecFqGY4Dvkfpw=,iv:BrRjduGhalW56R71XudFBWRuqe1DHzBA6MifqSrYcSc=,tag:pQLDxtz6QeETpFzqf6IHoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T10:25:11Z"
    mac: ENC[AES256_GCM,data:Kc8rbo3GZ0IkQHgK74/CfPrWCBswixy2pO6VE4rAXlGcPW07MPE8KgGUM8Q7kXR1yu5OkuW7XmARF2HCfWCNQMpRTRrWIzWA8ztR22/phIautzWXTl6qerHDyq+5QGLoTZ76IfLKzNz+eYakjN240MxQb4uUBYcHdqaqi3IFGmY=,iv:NABg4T9sM2FhTWmC7ImT1AtauPl5PTucAq14nRpLFLQ=,tag:pjO64uKrIpZWihRrmZ78PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
