apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IHo5kPa68nh84dPBZnfIbDPzJOX7CKgUSSgtqE5qx212g0TQ,iv:E1xZT1e7eDPEeadDUur8Z5IF67HTSM9iokp9GrKo1gk=,tag:4PylKPfytdN/cRxbtCwkhw==,type:str]
    credentials.json: ENC[AES256_GCM,data:RGfP/3NvvaamFpzPXXCPG6C6CQGoS8EnQLaK1OUQujc9ruRjajhe03DkpsZpVhNei04rcj28VkVQe3YPE0MUKJFSMxxIOJeYMZmiz0XeGfKiQ/y8zqS/H9k9GfswajF8oEBB/FXunb+FDvIHyjeaM5OGzcxeOVpusG2L/bLeSMcYzADOPZmTyKSZkebhf/MxaRITx4Im+uMiegCsrXjqPOcu92m6A1Z49HgA+0cRjQ==,iv:BafKOMR3ojvLGUHezHHDVgiCbh/ecs/sOv0/oeyObsw=,tag:xqNiaT8/ZwdWTvtPtkoPNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiLzNVT3g5ajJPMlpWd2VW
            SHJabFJySjhHS1JzOEdCbDloMnhrNlQxNEF3CkRTMkczWmxsRjhwQzJYT3gxaU1L
            NGxpWXBvRlJGanVxaTZmMnhqcmxISVEKLS0tIFp5RitXWXdPcFh0RGU3aHF6a2hV
            U2hnL254aitYdnNFVTM5YlFoR1FNMUEK5y33zajSPQvOiJYzP52vA25SkLzWIOp6
            OzhaWJys0+ue19K1EYF8/mYQkOCx7ErAbBhlMyEpRqlSUqWBU793DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T14:02:40Z"
    mac: ENC[AES256_GCM,data:YmngBAWyOKbRn+M7o1TGeGW9/zDzpPALcvSBn6jGjZpxdrOrS7ogSHVuC4eq/JKy/lp2byDp+v0cncbXE1ijtfzQfPROFmMS8eiBMlA5rGUZ7DvUTIFXvZwm34OWiH/8tggaazl3AGYZz16t9H93KFKolFkrL+3zljcUB+QQG/I=,iv:sfen4g+pDmFUhR2lLrysaClhNl+blOtJZ1dFCigNcXU=,tag:PVKiaGzyka8XGX75kDXcig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
