apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:r1frSyffFKkpmca3d+wqN41gCtTBDhMofStBRsuQ/11O2ZMp,iv:wfXPpD6E6I/N8txF8ZWG1MUHgDl51uaKlJtsn304FGU=,tag:WClqyuWd4DLt6GXjcxrL4Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:FwMDpI5Uokw8U8n4J4BaXWXiQRBL0PgF/9aPuQwHxQ5C+OTgSPIbLc1MahhW2tW2F2syMHucB9uUlt+mSdvMygSD3hG/JVBYxX1pXMf3HoRRGkxjr1zJ1j2u3ku4IXx6SDp6VWZ4XaQ+M+2Eaviz8QsRSQ2ZzHSSJAH1zTmuW03NCx7JbbJl7I2HnX5aUz0xa7jO6wkdp1a11Zxamg3fTpPadsw48DRJd3ujwJuFrw==,iv:q/KkhdF0ENXhIcgrhBa8q3jlgNzZuMyz5H+lNptZ8Mw=,tag:sNjSfin24xRyC8HLIYJsiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZjFFdDh4TFBzTldEL1Na
            Y0l1c3g1eGpCYktTMDI0U2tTOSsvamYvSkJzCmlteGsyRk4zMkVjakI0QXRMUGcw
            SUhZNEw5c25oL3ZueDVlS0k3S1ZhcWcKLS0tIDBvQmg4WGxkWTBsRzRGQ0NHSkx6
            cnFtVTlaN3g0bVplcWk0OU9nRkVwckkKavkbMK6hmI+dR4Xy8Mzzfj0D46beX5Es
            REa4hv7cAtH2oFYzR5k1VxLpPaj7MHA2b0StVKzvUGWUz8uU6+xJrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T13:13:58Z"
    mac: ENC[AES256_GCM,data:7N1Ko/XbQUDEw7mGfFr7O6vz5JQsFyOGREd42giJumryDy2diutnX5RLcym5EP95y5oYxsbN2R2XQsPKYoWgy9sJATlImhkhWVuqsnQQdTiEwnoAdJ+CM3amQ4ksjnCo574tn+ycYLW4UukkgLZmenO74YA0d6GXmaDCC6qOcHQ=,iv:h856DJ3v6FbWAMD10QVjCMxxOd/BN1HjRs3eSOfcjs8=,tag:UFm5d6PgAvFJ0jmuy9R2mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
