---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b3d7e3e8-93d5-410e-b5dc-b1c000c9d53a
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b3d7e3e8-93d5-410e-b5dc-b1c000c9d53a
        property: password
