apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gMMOF7/SFvU=,iv:dDvCo0TEFlX91YPiqBWHlCo+DFw8eJUikMi3s2vuvNY=,tag:xtphNTilGzXmB5XZwOtnhw==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:+wTxQGTZQg==,iv:3ulqRHt8LLZc2qhLHmxwjvogqaq/6b5mGmNpy095GbY=,tag:cd+kRPgKzPJ+RoPkuuORGg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:5HUrtbPHyp3pQo4=,iv:UgKkaftHOjGSTNmauM7BaZ+IqKc/qtGtbZbo4JGkT2E=,tag:9x4WufD5N6Nau8rhUBjSFA==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:3jnXjog0uHmX0cduuC7xEeqP5236ht79CzwKNK5oPiA0NqXrN2zVyghhmw==,iv:Bpl2fLeop6UXS7nHEccEhw0TJSSefhz7A+livxUOhV8=,tag:i5ql1ZwRebOQt7vRfpuTMg==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:aQlLy3OrbA==,iv:1kzLhos3EKw7jdi0F+yJYS3/pCmil6ARwNZcmh9yovY=,tag:gGxGKaLgYXw6gF8qfedpfA==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:JjB5yzTCqg==,iv:uL7DVwgsh69mVrcrdAivM4Ixc5SKKRmMzcjUnaCYDt8=,tag:wo/vHkyzAZAxgK6lFKFbaQ==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:YxOYzqGXe1M=,iv:xeo6C0lFO6T86ksw/eMMon1JIj9+lwvmiDuMiTF+2Cw=,tag:GgiZDGM5QmV9rSKDt9bHLA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JIgiWDFFVIp/JwCd,iv:24CiymnoXizy3oz3h9POvVjF4nLjv2z4YbuC5qQVYlM=,tag:uAz+s0ORFC3tNDtfrHMBpQ==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:mKzZoA==,iv:fyrseWyCkY//Xi8X47zTQI0vFC6g8Ozj+PTMAZkTZBo=,tag:xW2Y8GbTayD5zHtR/K9M1Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:NRGyBVDYgKcNWT9Q9F1jE+a48tiEsvp+6dsspt4aU1yPLHOl26PwqMSYtH5Up7M8mMpB5O69/i0qJQxppcTZtOd+9q+x28zUhkCJMPQW0V1I0m6Mr3HM9GQ3PuQTEEeiUqBEA0QqQXvDbllsrTdR9eeAw8HIfBDon4p0CEzOmYBbV94=,iv:71sVwCHzg55FTc3WFK25uOH6woJK/W9NDve6SAUtFd0=,tag:9VwxcpA0rguyNmb7aUSuCw==,type:str]
    #ENC[AES256_GCM,data:F3ev6iABD5eFFdpnVQQ=,iv:dXbmxWvQNxqMhq+b5YuiHL/nEl7JruNVfhfMgTL5fDU=,tag:Wwl+5qKFIyfjt7i6BirEcA==,type:comment]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:nb2YC5U3RA==,iv:JEnZCG+5dlt1R02X+YxLhgk+6NodRFBAnfH9fushgKk=,tag:Gp6/uEQoRtx2R0MPc1VSUA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:MyBI9CyfdyB//uw=,iv:y4V4b8wPzV0AlGbgqjTy32whNVhVhAVE6Q/AqmRzgh4=,tag:DOn3DVPF3Pvjf4Mv9bRZBg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:YNhO3s84xChD2nd7czSTZVHHYtamqg==,iv:KbawyZHh1FI4/Q2pu4vvqq09oSyLbFzk1si0ua2tNcM=,tag:96TKRgRJIToAIo8SWUtYTw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:90Ot9Miv/w==,iv:Nb4JbTeNeAsgUO5jUo9UwvDme7R2lyMX+9/yVK0TrMA=,tag:wWX/2x1/QhqACY6TDsArMw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:71NorTaqu+xPOsDBwdAbZc8+8Z1rF1ep7ASpsEFDlCPiz6Ap/R0=,iv:RBkb6IZIgR2GtZuEKS3JgoJQunpvglvmrR3lMMmyS68=,tag:0ylvrztabFCspaTAesb+9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T18:14:21Z"
    mac: ENC[AES256_GCM,data:86Y843b03OsHArXqduN3tSlsNdBrMPPsw6s6N5J75T80N9hOOX8rpZZOIZrCr4F3FE4UkBLCf8bZd4fJn1GqYL7zKx0EVVTPhsODkfsP3PhialJodhufBEz4iPcNcjvUn9PKRE22kUWBLDxs2ZfrKkgsQxnY608XIBiJgqyFxK4=,iv:VDvIYFwNTjbBPJHDPAJ9Zhj1D/IKPBtl9EK8RsWRKPU=,tag:ck1Npxf29XkeIWMakw/K/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
