---
kubernetes:
  children:
    master:
      hosts:
        iris:
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
          ansible_host: 10.0.0.13
    #master:
    #  hosts:
    #    mars:
    #      ansible_user: toni
    #      ansible_host: 10.0.0.12
    #worker:
    #  hosts:
    #    iris:
    #      ansible_user: toni
    #      ansible_host: 10.0.0.13
