apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
type: Opaque
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:IHMz+DnKeBPFZzZb52A3IHLJHTI=,iv:ze9y7XE+gihD59VHFws18WbP1HvM9U+BAPCBc4IaNs4=,tag:3e4Ef/Z8DWaktBzI722fKg==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:fBjGAo7dXZNgxe485W7ILnVh,iv:buzhsurIcV/RClFGmfzAXCJx+iPn9RChK8de82LSBCc=,tag:LCW7PKqvIGdpi2/BS008XA==,type:str]
    HASS_MQTT_SERVER: ENC[AES256_GCM,data:9K4lMS5skE4VSo9wLmdZqw==,iv:s6UqJX8mc7/u9ZzsojT7scTXloSpsj+1WDicwa+2yYM=,tag:9mw73z8FYA9eYztaWK4lJg==,type:str]
    HASS_MQTT_USERNAME: ENC[AES256_GCM,data:yvnsRQ==,iv:h0ybnw3jpj61KP3w+DkZNssCqTkFpRQvnQXxeAymMCY=,tag:n0z/RV8whAg4B8Pw+jyZnw==,type:str]
    HASS_MQTT_PASSWORD: ENC[AES256_GCM,data:w7BiZRJcdXGJ6aSWqo0=,iv:KsY1rtXkbe7cor5Zemlsl1aP4Y0rPaoWYbTP0n1SS70=,tag:RhFvnD7lf+OwhUHZBn239Q==,type:str]
    HASS_MQTT_PORT: ENC[AES256_GCM,data:1hNZaA==,iv:tp9ITM6fUVjqMLv69u5x0aCXIJq9Mg57Q+uDjJwg8tg=,tag:bBRqYQ5T6P2uvvLDFGPlzQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:5LyLsviajn5/hXl6Qek=,iv:XWmP3yg2Vq/KZYdbNPNMYp3o5fdn8YqpYaEj5itBHGQ=,tag:jRiPVpd9AhsRLNqhQFgVJA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:EDQMTyxxGl28mC7uFic9FhjK3991SuhV9crBaf133I6wAg==,iv:C5vM0m3RlX3nP5g+uil0UFDcYRzKAUnqoZgAz/pAzWs=,tag:xU76eGawZ8jDBk0dEO64sg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:l1klZA==,iv:nxYtCZ/KDjjIpEkhEFcJ67+npy/JdSAouVk6/HLOwwQ=,tag:3fyCN5NIVDi0V9yp/SmkHw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3tRJYQ==,iv:bGhpmAb3WDit+bwAtZVd+1DM4fkv7hNfLh9sv+DRKSs=,tag:cFIdAwxyBzUUK+w1BTjC3w==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:7v2mtoEgn/yEjCBLzPg7/ubwhyAsye+3hMG/zlxQW4kPJILhpjm++BeU9E20JmSYPWWxYvTPVq3i+PNek4stsp8HFfS6/4Qoig==,iv:QKFevHqpSi008F+oaY8/BezBd5Ob43kjwt8hdWHzUUU=,tag:psmKHs/5Z0dLlG5GLIsIgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T18:52:10Z"
    mac: ENC[AES256_GCM,data:fJwfg+oLvTK35RkNhxuk/CYNn7HczJF7sP4OjUmUV6bYwTz4Fs/z2jaAVgnCtXV+ngzkW1lwTCL0R0Tvn6VacYfv61enpfDZLUQMf03T6BoaViiK9WUwrCxMzquzvBhEMH8Bn7vP1mcJjHXZnEf37YLbCCxkK/0FL7/bi7hhSdU=,iv:mxbojtvTl9B3ED6f5owuRI+9d0U7sVi81d3bZYXF7Qo=,tag:maI0Aj/Mfa/mPWnO4wGxMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
