apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
type: Opaque
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:f/nRoOfISasLutzaIqOUdYjrFM8=,iv:pMwQEdKKpX1nQ724GZXRoFkcbpQKKUyhX3hoB6vgTgY=,tag:0ga+TvVTK+lnkfQNWCg3wA==,type:float]
    HASS_LONGITUDE: ENC[AES256_GCM,data:gFguTArj88XnZICfeeL3MeMD,iv:97lXIDiltz9CrCjLmEAE1kU4VzOOsa6OM7WdPJubLrk=,tag:Xx4XvyOJ/HHUnP2F/OBxZQ==,type:float]
    HASS_MQTT_SERVER: ENC[AES256_GCM,data:9K4lMS5skE4VSo9wLmdZqw==,iv:s6UqJX8mc7/u9ZzsojT7scTXloSpsj+1WDicwa+2yYM=,tag:9mw73z8FYA9eYztaWK4lJg==,type:str]
    HASS_MQTT_USERNAME: ENC[AES256_GCM,data:yvnsRQ==,iv:h0ybnw3jpj61KP3w+DkZNssCqTkFpRQvnQXxeAymMCY=,tag:n0z/RV8whAg4B8Pw+jyZnw==,type:str]
    HASS_MQTT_PASSWORD: ENC[AES256_GCM,data:w7BiZRJcdXGJ6aSWqo0=,iv:KsY1rtXkbe7cor5Zemlsl1aP4Y0rPaoWYbTP0n1SS70=,tag:RhFvnD7lf+OwhUHZBn239Q==,type:str]
    HASS_MQTT_PORT: ENC[AES256_GCM,data:qw/MrQ==,iv:e/aXWYM3CXmNSCqoJ4EPRh3qq6NRKnEYUJMo33aS9Uo=,tag:PRZMS4LsLMRzxqiLY3z4LA==,type:int]
    POSTGRES_DB: ENC[AES256_GCM,data:5LyLsviajn5/hXl6Qek=,iv:XWmP3yg2Vq/KZYdbNPNMYp3o5fdn8YqpYaEj5itBHGQ=,tag:jRiPVpd9AhsRLNqhQFgVJA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:EDQMTyxxGl28mC7uFic9FhjK3991SuhV9crBaf133I6wAg==,iv:C5vM0m3RlX3nP5g+uil0UFDcYRzKAUnqoZgAz/pAzWs=,tag:xU76eGawZ8jDBk0dEO64sg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:l1klZA==,iv:nxYtCZ/KDjjIpEkhEFcJ67+npy/JdSAouVk6/HLOwwQ=,tag:3fyCN5NIVDi0V9yp/SmkHw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3tRJYQ==,iv:bGhpmAb3WDit+bwAtZVd+1DM4fkv7hNfLh9sv+DRKSs=,tag:cFIdAwxyBzUUK+w1BTjC3w==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:7v2mtoEgn/yEjCBLzPg7/ubwhyAsye+3hMG/zlxQW4kPJILhpjm++BeU9E20JmSYPWWxYvTPVq3i+PNek4stsp8HFfS6/4Qoig==,iv:QKFevHqpSi008F+oaY8/BezBd5Ob43kjwt8hdWHzUUU=,tag:psmKHs/5Z0dLlG5GLIsIgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T18:41:46Z"
    mac: ENC[AES256_GCM,data:SQBuRpkHcdMHsPy9iWGEc8D+MurCbP0x+oWd8fBaaAjfHQuuQm/gwiB+e3li/VJ4Gp4XY4RkRtX1abnncDlzYdjzHkXDraqbLVpoC5xrgix3SNrtx1Ret8o0QMF29Cm/cH+enzdfuS31/m81ZcU/XkVBCLw2gnWvBRAF4B7EP5s=,iv:ifCK8C1u9hMsZ6XAOlgJj8EXybjOjgefBFR3A1hBrzE=,tag:NwPckZUNB0zxk2g4ShqmzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
