apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: security
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2kAqq8OJgznv,iv:h1XTCq9dGycEcGSQp3rRjFtH0D7Ah0CGT3eVUihmn9Q=,tag:bYMUlimQ4baPceCsWdAfcg==,type:comment]
    #ENC[AES256_GCM,data:4I25pKkRxdXEPQLYvypLGi/mCY2rBDOroSr57ng53lUqTWXOc7m14uOhvOHVnTF4LRGax96LNpFZOH4kMePGoeh1jVXQcL21O+9bUTE7zhtT2j/syKY7GXSZfjZ3nc2RMjIogik=,iv:wS1eAikXfVY4rY0mU98HIn+sD1WtakvvKSf3Ev6N6aA=,tag:CsFElw/00ZJl7RpfXEpDlg==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:7xx4olQSgGfqIC/9PbGa7SL0tq++ASX10eLvYKY8d0e7ruS1BkWYUoUZC036As2HwIzc,iv:R8aXLxp3JSI+EZJAJrcrDHw1HL/23O3S5d7T7rnUL1w=,tag:jMBdaJzeH7mwaIZpS6zs9Q==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:Z7YbI5IgMBhBHt8z0aMB5r7iNRSdgExVa3xxb/Uyrkg/RtWkjEp8MAJj68GDKs146PLeO/NQNJl8aQ==,iv:dfDr4fbZmuZFe8I42s5U7Gj79Cy+lkwQ0rOBcjv6OXY=,tag:x3G5uu/EdCuHMqhQfU/lTA==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:FeuRc6Ge+r2JgrP3lPqNUeGoKfTmP7bsp7asOppsmZ2qRRIOmfYaFsUoPXlsk3Xo7wqncYw99yYlLYWMS51Yqg==,iv:1jsjmYC95uGYQxzFkOLahLfYo0CbC6U5Z6UU+azds8g=,tag:iZVTvA48n3u4d8tcoi334w==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:STG7XMz42NIrmybWvuYuiIsBn4nia41/XpUgggACtZdnpBPzgKiSnTceexN/QjNEWfnFf6xJ9QJ+3jSD0dmdrQ==,iv:63Dcq3LgIEdRjxOqVz07lAS70A1lFqWh9E3LttnbNLg=,tag:wuzde8xNf/Bmc3vzTRiaPw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:SWmlJsE39Txhgrp6LeeW1MD0lcQrKBntUgjVlr9viKHzWWNu7tpR3TRt+9glT5Pb/ypCarS4+HUld9nATKT8CA==,iv:jAsc5rqoFS+Q2HbGiX+q4EHRHHzyHe7x0ugFY+5LkaY=,tag:gGWmZYFXsazeGiAefMrh9g==,type:str]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:9JQwVYUCWas=,iv:welASI/rHvwWkxCJNr/7HanzyeVohreZaU6NdHS7uGY=,tag:AH/KqJW7QLj/G9TcZXvVow==,type:str]
    AUTHELIA_STORAGE_POSTGRES_HOST: ENC[AES256_GCM,data:J8WAP7XWbOKoQjNQZCHiu7msAz0lYIiTGFGP0Je4JxXvH3FPEg==,iv:UrnlKpPz7OjTRtQqugCZdHzYCI4DGppbqdeH4BsDA6U=,tag:H/2JNJopiA+o/PKJ1HZHZA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:sVx8SubQPoJdBjc=,iv:+VOckCNN8ptjEQm1x2nWBSdYzELMp276fcX86ZhJ9SU=,tag:3yFuI9nzRxsiyYpB4BTjjA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:ouzn+MzCHPk=,iv:uZ9jHqi7ShuTyw0U+v9kdULyyZhzVk0jMv7Qhd/a8y8=,tag:nLE31HkVWrZ4h4rJznWmMw==,type:str]
    AUTHELIA_NOTIFIER_SMTP_USERNAME: ENC[AES256_GCM,data:ShnXrQx2OGLMwgX/enF2UrBc3EKA,iv:rHEZMjxKRn+1gU4zIctwi+GBE0S0CfQ7YvMwJpKMkf0=,tag:QPzztBdS/5VTMSAoRkZQNQ==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:I66080Yk9NDbiejoSKZF/A==,iv:Hn3dVwJRt+BM7dA5YtWGTvW9y7c6KKxpMZAYXJm4zgI=,tag:g0msSXV1RjsiM6IvKIQlbw==,type:str]
    AUTHELIA_NOTIFIER_SMTP_SENDER: ENC[AES256_GCM,data:DLNBF+TOhNODPl4UqoJBRLlW3cjp,iv:fpHMFfNfEMREgELRfhdO6ENNM9IPUUydTvtpJc7bPjk=,tag:A0OU5XVkLUooTv+nmZ1xWw==,type:str]
    AUTHELIA_NOTIFIER_SMTP_HOST: ENC[AES256_GCM,data:ZD4Ox2QcYeImZGWw8CU=,iv:M1SWbGQvuOQ71Gb0rae+FKbeRmH4/0Bg/OTjvPFPTbc=,tag:peZMJjiGhEWsqzMS/8PINQ==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PORT: ENC[AES256_GCM,data:4eaA,iv:GhSG8MHFs0SxZlDiOpxL0c0P3Wva0ORRvr419A6ALhE=,tag:jv4OjQF5d/vg/fLSmnkzZQ==,type:int]
    #ENC[AES256_GCM,data:vNHhFjxYSng4Qg==,iv:Wta4RA0dxZC9mElSoeIsPRdVN/1XQ0Q+TccierxVPiM=,tag:Jv8VtbAgF1RDz/EjMmrqnQ==,type:comment]
    #ENC[AES256_GCM,data:CcKBQkdDYKfSAXQFIexxo6BUDr0EISs6WMrqtlGenPvLqqHXSGmo09LmPkec80uEczFltGPWReXD3xbXX6sbmBk=,iv:iFHpxMQbdyL8D302fQGBBz3w04gzQyHJJqSmEErr6o0=,tag:6KX/4luWnOz586NuG3GW0w==,type:comment]
    #ENC[AES256_GCM,data:x0lew19saH7jA1wb1kWu9IhHaKeWbHrg0/qfgEPdHiozMizNojs9XqeYUUnqh/YL/W8dShEjZKDT6r/8OGov,iv:O6PgATu4W0XxlE0fCcLcSPkFMPZm6gl2p8l+lcwab1Y=,tag:2wW+c5mhYl7VLrk3NnrLEw==,type:comment]
    #ENC[AES256_GCM,data:CBmkb9sSZeztYVAl5vr8Ty3hei8Ls7aOrufkATI5NDjNlerDqIDjxoIbJ36s1akKpm5beBe8pFIXTjo09lUXb5G3eg==,iv:55v925qUl2bVQadKTQa4SXeBI4AhPqb0Jyv2cQka+uU=,tag:/8YfYBL/xBrY6MlLr56x0A==,type:comment]
    #ENC[AES256_GCM,data:WNrkImOw13n11Y62+rvb0YUem/jYZZ52Oxz2UXzSa2xyGWRSV8XY6AjHHMi34Eat5s1nBr8KhWmxdnoHn3ut+tMYhrqYJArJJQ==,iv:m24jNdxDqD7qn/mV8x+90ustIf01rJJPZBaTbk502RE=,tag:2wk3G2iex8s5Tmzh2CJY8Q==,type:comment]
    #ENC[AES256_GCM,data:WGKsfFyzu6uVgWJ/mVBtjaDomSYIOYzlc9n2Ix/elYXno3xM2WON5sGxQjIdhz0froveWxb/qEUSIpEEUA==,iv:OJKIQZSM20JnifJZLWLpzYCDHaB6JMTRq5zFwdmBGSw=,tag:g86TG9DWHdLV0XOf5PXXhg==,type:comment]
    #ENC[AES256_GCM,data:9M4trajulJO5DBUqATU=,iv:kowV1FZgvi0Rdih3CiVsARufTdME76F48lBQbwf8kos=,tag:npMEWbtXVjqoQLyw7mJA1w==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:3M3kvaLfRNw=,iv:DlbdJbV4hfHR+yA/9EkWRHDP1vrr9mpYKnh+e0mlFpI=,tag:smVDOIPpZ+z2cBGTSUwJpA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:za2hQriXeElF3SkSNqT+DSz+Vcm6izuA81Z8FZkWxDEeO8k9+A==,iv:wxLMTtbpa6UHEx5dkfsa8rthhO6FkrTq+1aZBFfyXiU=,tag:iW8nlLn2vTV470kA6M5xfA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:0DhljyvT/MXhHwE=,iv:SWx4Uu0i26S8sEL3KmK00Xh9hlZWUs1Vi1jrCMSd044=,tag:UbPwe4VL6uI06c0TQuDhEA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Bi7A/58ypvCQWbI=,iv:wlWHfduozRDuNwx6nc7jHJLrrfswpPGiF9JNbsBmQ9c=,tag:FvIqpkrQ8Ik5227VmtJRhw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:UMeeeIXoWoI=,iv:oeFnm9TOIYWf8hE41jb0wwZqCtWMywTYa9TbfmjYOrU=,tag:if33j0V1keb07vzibvgG3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T03:42:51Z"
    mac: ENC[AES256_GCM,data:wxxgXuer1cW9A+R+JwwOTaVoc87jjLABnnkUE4EhwQX0Y2n/nTtddk+OAZyWu1TQFx8thTdtRRx/xSey9Qr7OcY/W79/3ibIPQnLVI99FyzOMk60rU/xdhvmhtiyvNJobmokB8mvQx1nmizPvXgEW3494o9xDZMfwtUZkT5VzeI=,iv:RIlDix9AVK1TZ1t0kmljH1mWEzvpuYv8BXMM52e4g8Y=,tag:VtrmEfIp/H2EmsEZV//Law==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
