---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  namespace: home
spec:
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
        - name: openhab
          image: ghcr.io/kilip/openhab:3.4.3-config01 # {"$imagepolicy": "flux-system:openhab"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
