---
default_packages:
  - bash-completion
  - lvm2
  - nano
  - git
packages: []

install_docker: false
install_haproxy: false
install_squid: false
configure_certbot: false

nfs_exports: []
zfs: []
zfs_pools: []
zfs_pool_options:
  - -o ashift=12
  - -o autotrim=on
  - -O acltype=posixacl
  - -O xattr=sa
  - -O dnodesize=auto
  - -O compression=lz4
  - -O normalization=formD
  - -O relatime=on
  - -O canmount=off

emqx_dashboard_username: "admin"
emqx_dashboard_password: "public"
emqx_users: []
emqx_static_seeds: []
emqx_mqtt_port: 1883

omf_theme: "bobthefish"
omf_local_path: "/home/{{ ansible_user }}/.local/share/omf"

install_nvidia: false
nvidia_packages: []

homelab_user: homelab
homelab_user_home: "/home/{{ homelab_user }}"
homelab_user_ssh_dir: "{{ homelab_user_home }}/.ssh"
homelab_user_group: "{{ homelab_user }}"
homelab_user_password: ""
homelab_user_ssh_private_key: ""
homelab_user_ssh_public_key: ""

install_ntp: false
