apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:j3I2wAQLSKLhdvtJErWxFdb8/zA2w2iIqNcx1fOXCEjLdB4JQhopIg==,iv:4MwIKkj3oJOZsAIaOfTS7lXcymbRO50rk5yRFN7A/aw=,tag:4NXJQ9XJJj3R3wRpE0+Sww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdk94K1FaSTlXbWxQa0hX
            cVBNeFBabEVCUGdvRTBOK1dTNGZ1UnlNZWxJCk1BcVpHN1hCMmFRWko1Z0VqSVlG
            aWFHb0lVK3Jnc2IwYVl4UDgvTmZ1akkKLS0tIEx1aDh6K1VtV29wb3VvbmJJWVEr
            cFgwZXdnMjdsanBVWE41VEQxaVAzUVEKMdbNFiwE5/0p5KO1pFJ8+vhUFkJxXa+k
            n5BO4jOpdW0RSA0kx10Q9jzeZx61WTNEg+gYT+W2l3+gt2K88ynsGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T13:13:58Z"
    mac: ENC[AES256_GCM,data:AWkSN42g+eS7vq5yNqZuqJBwFGpl15iLTMjnUhjmUBzFtNhc68XF2A54tUVC6478nmq5CwJVJImsSQNHS97SgpU3KhhslIBsVs5bccCThct1+sUzqIWviGaYmwwjU7dzHTPC92VTn0x3khi373sz7mg1K8Cy1na2VH42K+b8i8A=,iv:FBqH0zUPYa+Qhw5KBZtUJRZ00b0ZJajNNNR8AIyk+kg=,tag:DObl3KYnXRk06GVPW4ucjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
