apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:N2auuwoAf9mqkzbCklcptPribROM3WTkb1T50UWNbnoIL2A/FykLWg==,iv:zthWElBwafJeHuowD/zvu9buodPsWw8vr4W3LbgtZMA=,tag:5fMNRg7OTbO5hruOCIrJrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWnRTMER4U0pCOXVDMy9a
            YlphS2RySTlmZUdMV1N0UVBTdndYYWRrbEN3CjJ5b3l2RU13dXZZMnQ2SkEwU2RX
            WkFXL0NlbWZLWjR2eGd6LzFlR1JBakkKLS0tIGc2b1lsczFvMnNqNFMyU3hYcDhI
            K1Vaa3hvdXJHRWQzOEtyMGY1TW1tT2cKo9ZK9R8Z7Z2U9RshEOFcpGkoM41NkLdq
            UEKuhbHKCPIpcYzYPgG3rNMTOLtaeRdW050CW+P1nLGt7/ChfBOSGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T14:02:39Z"
    mac: ENC[AES256_GCM,data:jy02Mhl3ZKhaNlGlksqj2hpT7Hj0bFScFf7mWJIJ5j0UlQWBMTUOIdKRa8aq3ZgEN+5qKKVKgMoHaeffK3xlK3hiZ+O3DBf/ADz1ve+DHPn3JROqKuxaihvcD66WYyP05lEejmbuFHBfRY6nOIEfQN8jtkaev/BWRqf2zaUjNsc=,iv:iuuuVYbq0qVElb+CpgzV8gbMmpwkkXG2CjNuDzPcqKo=,tag:BotVFjAuPnZnGmoJCL1P1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
