apiVersion: v1
kind: Secret
metadata:
    name: telegraf-config
    namespace: database
type: Opaque
stringData:
    telegraf.conf: ENC[AES256_GCM,data:FbTBQGc1P7c+gtbgrkrbHxPQufp4DY1F0Rjh4NmhDKFCr9Fq+sdQCr8mQfakwugxe7Lb0bwGTmQPMKUAXxUltC/IWJXEnM8oZeIWknG3P4+YH0e7tM3PwgD7AVp8j3Srz2yDLzIszCFRSlJlGqNjc7+KlgDLqoz+s9wRHTjklUWen5zfRtqm2fucYIVDnaJmnJugcXxIGyVQNiNJ0bxrPQCbQiH7vzHhBZZxYXtHO4R0eshIQNPU3zyosmAa2Mjy0knw3v70wZVpNXU/KF6VEGGgIQz27RWLeuVavfKvEgWr/2lm9FCiAguqUPq03yMyioWVoGdLc4IY0h41T93AysEBLMVuPZDKsUr6PrcT8z6Xzr/ejDqD4p4t3o3/gWmt6fRFljxoTHoV67HtkNwui1b0DzQsghzQNepMiBMZ58zQ6fKgyadf7lHjX8Q54/HeHsWgsFFIFhaQ+6WwcGx5xLva43jr4soIsEFWfNNdIpQwQvF3fTmOI8b+i5I+hlczUG9NaAaY5jrQRn5s7oMY4vD/VbWIUmcMR6+MKxsg46ASbXrJaTlh3Z3HCxZtWn3r9EXLMCeWXIzr1sMgaxSQq/CULDpJhdnS,iv:wlf5o/l59NsIpQ+GBrBDbsSPoDgIE2VO1SZBd/jtFIc=,tag:MfgzrH5Xcr+QfkI0BpNr0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T11:27:45Z"
    mac: ENC[AES256_GCM,data:QFdZqGhsXEkaxFR9qbHk1P2MSjVILk235yo8nXaLxTthl0k9maBEeBbz562Ol/yPJ1ApPlpjhuKPt/BEcUtIyYanvgZVtetsZ9rUmC4ytjs9jnKO3HG+i55mzDaKNoEUhVHvKl4RU3/awjF6Da7MRk8//aKOmWH1In/zx3DoCVA=,iv:sPa2JB7zYPYKWP00mrUR15/DSNRvP2gt3Jm7AMzh/fA=,tag:UgLBdG6iSISkLSHDWOB2TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
