apiVersion: v1
kind: Secret
metadata:
    name: telegraf-config
    namespace: database
type: Opaque
stringData:
    telegraf.conf: ENC[AES256_GCM,data:pxukoPSfexcUnfXO/LuJkFY4698QXhhY9by4klU5WyvRIzws6CjH1bMTkfAaVJIqOi/EA3hXvyowu8aPs45tbwY4iZnsVDEhRmZq+8ZCfaSrbJyJkDSuXVgyfkD51zDwprShNcVZayflq3d9MZqOzxAy2/4uvDMWeP4dLkzLR5nlZt6z6If4D6oilCaAVMUXtTZPdPI/gUf4SwsG/DY1Me+jolV92QraaZg6LfJNtLO/i9Mhfvb/I/vtMhE/06HgEMK9tmBkrTyjU4KLJOZiQE9/o4sen/hwBlRj9VgMaWg128yS3rRAGmBE1LqZjcIguos9o7/fdzBOIdjpYSWEUI5kfT6PgFpKL2VFqUmXatpQ/fwOeD8cZnK086kSjZwMkz161mohetBReZ+UsbQmLM7/JvpKkMOmMUUUYPOSrOACrAp0YoOZkEvye/zj5Qa4EvO/jZZ3FxJ/s54euy9o/Y3AsM9NxC7Qc+Q0VIQtb+xbvfGBs9wqoTUjVyJfy0QdVhdAxsf+aQcm/ZhAeyBZDAHOBugF8TVqCBxFYK9OjVu2gKMT9WB2NRG7PQpRQQKcW490eji7691aTSxhVmy+zFkaz8Szp7UfGJC+1nM/jP2Yr2qh,iv:NKBVCkP2cp1fxcp8orZjiGvz890zOJJKLPlwp9XFXyk=,tag:g6ck9uWsKh5YxBze65LeTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T11:31:06Z"
    mac: ENC[AES256_GCM,data:TW8swhfKuyPtyX55xGVukW6yK+AuKHUcyL1/2SNz/nVPZMrbtBPQvzKdcaVjm6Jtj5IDqeabl5Nwbm//jQ40qbXtpnA7h9Xmc7VKQjP5Dz0hYV5baUH9IiDK8BSGGcVfsOomFfQV1Xd4Tk97FBXRA54Zb7V0KylZ1yWxdHwdiQs=,iv:5Q4AY2KU+Ez+uHXpb0V3bgyCMkOX8XbiwLkDAG6fBmY=,tag:MgnwyTLxWtWk73O/9xVHPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
