apiVersion: v1
kind: Secret
metadata:
    name: telegraf-consumers
    namespace: database
type: Opaque
stringData:
    mqtt.conf: ENC[AES256_GCM,data:nHTMxpcTU+mPbuKGoZue3lLRPOro+3tMmknw++/XDLlBdoKLaub3/3liLo/wTNvNsmEHdn6Wrn9kLrEpkEvKZnzsWnmqHh5zeunjIGI6oaXWoBpzmV7ZvXG6Zx70RmnPz/PCGmQqW346w7Xr/Q5jh/BWEMtNVM378hpy3xWG46SF40CVWIrtdVFQAMHbtGEAQlqEmEmWeSfF/2M4qhQq+vYRQl9ysmuyKzVnt92HjcsVmAz9VaM3zrVsG2n/S/+OH9roiaS45FjuEph3ov1WKvUsGREnTwkR3w4STYZuhb3NHL74a+qazl6hCHdsZca/IU7MWmK3H2kIYOW7Zs1ein1uOg4vYIrNWtuRhSElc+xtcaX/wnu8MGJjVj3SdST+5HtODZ4SZvrbGtn7NrnZkFVPTVOj3LLVaDzAuROAnxta+39dGiTEIzMyvBs5p5gq2h9VI/LQ1bgBBAUz59b24YkNcsqi8jvSHVKzweRKdDc1ILWe7ljbJBeoq0pjNdhJJAjnYzSfa0ccPLT0w5xQWr3qZ01A4hN+zBR0yXjAV1IDbhhP1jnH8VYIissFmWKTgSoKexhIvUXg7a+K4oLKiZXCoJCMzKYdzZ/Da3YYMXEegSJkZhY0oDsCUuzDDg97AumRF20qf317Q6h4Y4VD7mmybQh+JMy9WjUK3tpMgS4O+AYKCaYQSc2Z4n8XIxv952UL8JUYEBVwH38/MSNsun3BMMhszHcri2uc3bpSghhcXhvciarrIKFRnTRrNqXoFkWEcUpfCow4FFfKQZ/T6lHZ5srhtHUpGMXnnuLOXJlycLa9aI6+ddhM2YI8HHlpMcXkxU5GDPbmghncWtRqa9hfBsGUzy8IEZJKnK7lG52oytkCbD+dnn4V4sTKsoovxgX8asp+CbuSm2qA4uoJCK3WU6m7SMImwP+BHEqHjWlXKxHZuAy0yXvYkQNGB8FpJsAwHhYt2NZ6MdoMx7qpyTlHBUFxAbNjddoMIqubbCzU0/no6jKpxaMmku/NY50Gb1A4m4d7mzILNAvbs4UuiAkBJrNrPWP1fYz+k1aUX0EZcoEyFEYzO6BF5aR3hWQr2M05ltbqAHj2VLwXk/K5YBVrQp6rtR16EgkRXZCmZEsuu+idqPXQ3U4WjKRb0KwNXYoHUifrtHnaD7W/zKF9Z+A5C7X+c3aLF2g0IrrSgoSwEzSr5B5tdXaCM/i4f4z4rFn/5bo77ItvjofdFgtDtHuvZRSQK/wCe5jLdQpw6/3LpH3QgYZPm6lRw2XnoJfuA83vZeN+vhhQdzhe9HEktdHieX9K7X0CTTIEhqd536UAwp4Fjdt21c712j1Ob02iRZPj4WwfsEYiEJuP5S2Q4Xc4PBt0QrwlRCPiIg7ow7qBewA7BIX1f38ARYRsMkVuCFiLruMewLA/Z6Rs8ShhCymaOUk3MIg2,iv:8s64JBRvVfvFPjx08i29GzGcb1EPZwqpl4u6UkCVucI=,tag:9pT4dB/VY3PuV2qvCd4rYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T11:15:45Z"
    mac: ENC[AES256_GCM,data:HTVi5afLhI7kLUIZoss7OZarczwuCx2trLtVk8Zks5FezfvL6GtWU29UJUDlyxDZ+cRytyi202pzhBydEeDLbDL5g+O2L6FQqr5x0zTvYCU9JXo4pnplARNI4xX7oOYPhlEZgcKyPXhdxHIi0NkBbyxFmR6+PjW7nMXDtw6PXWM=,iv:7ipoJVlDLszBY6nisl3r2KA4gOykh5Ng2MrwMn46I5E=,tag:itzTCeYxHWLYLN7C6mECsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
