apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secrets
    namespace: database
type: Opaque
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:apJGmw==,iv:D6IdI0TvzMBlrrgniPO1fOspD6Vp07mFwn3tH7qNqYI=,tag:NbJqSgbzKDymJJtaVYdzUg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:QmjzMM2MxAMJyU1I+wI=,iv:6uYPKMW8i+pvWdMxwSo1UhuwIW7HBYfJyVU+9dmfHlY=,tag:G13hDN56dGZiUBNxvnnpHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSkxoUjFIQjY4djRncnJX
            TU5zM0pOZWIvTXB3RUI5WHhlaEdrQ3FQUGdZCnI1VUJsRVhEMzUydG5kNVZkQnFy
            dUo4cDhjdjYvRDU5RTNrZDJBVEh5SVEKLS0tIFl5RkJOYWZsSmNKSFZlbThhbDVY
            K2tDUnl4VWdDOUh5eWZjak96a3BPZFUKn5u2gY4xhHK/LGnn7Sxt26daJk8J9qye
            9EfcnUFbCEz7JaWmjZHjkVkR9cYJZApk8LmLE+UjaiNIOw66nAjUng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T09:36:38Z"
    mac: ENC[AES256_GCM,data:6JH9m3u2HddKlgLj2RJPHvICm6GwBII6YwuIOCYX6vu63hnUiGyyj8PEc6fWTepimu0aI8A0HLIGlu2KrEKd/qSftYlmteUXD3p7phWAYWt6/p/2eT9hMem1F197dMTbq2tAirSN7St0trAont2pkhzF9CGdtJVngutYqy1H8EM=,iv:cRziwXt22hLJNpOwUQFHPy/OeAHYiabfzdtcowNsF/U=,tag:c9XHIJgLAwbrA/sz4vuMSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
