apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secrets
    namespace: database
type: Opaque
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:h7VGarEktug=,iv:Zzo9eSWPNYoVPJLwiF/elWifcNtVpO41RsBdIAZ8Xio=,tag:MBmtskDgiYNrvZx9cjGc9w==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:QmjzMM2MxAMJyU1I+wI=,iv:6uYPKMW8i+pvWdMxwSo1UhuwIW7HBYfJyVU+9dmfHlY=,tag:G13hDN56dGZiUBNxvnnpHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSkxoUjFIQjY4djRncnJX
            TU5zM0pOZWIvTXB3RUI5WHhlaEdrQ3FQUGdZCnI1VUJsRVhEMzUydG5kNVZkQnFy
            dUo4cDhjdjYvRDU5RTNrZDJBVEh5SVEKLS0tIFl5RkJOYWZsSmNKSFZlbThhbDVY
            K2tDUnl4VWdDOUh5eWZjak96a3BPZFUKn5u2gY4xhHK/LGnn7Sxt26daJk8J9qye
            9EfcnUFbCEz7JaWmjZHjkVkR9cYJZApk8LmLE+UjaiNIOw66nAjUng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T14:38:42Z"
    mac: ENC[AES256_GCM,data:qawlDvinDZgDg4y0t1LpoUkBE63BAPAss7ELoUv4U9n9rgJXprtKdSTo3+NsQbZEWixoL7T6MJslZFXkJOH4oKrd8tlCIPLzM3wOk4BxQMqxVlbsysV3U8JOehcWeTFEakksF02gjzAu4S5Z6GGjuLcZN0SzK3pbQqZrckxcgu4=,iv:qllf6DJSH+tbKoZwBXgE2BUGUzdLNgrndmOBM9tzGog=,tag:8QRGKqgIb9RVm8H2y+pPcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
