apiVersion: v1
kind: Secret
metadata:
    name: influxdb
    namespace: database
type: Opaque
stringData:
    INFLUXDB_ADMIN_FOO: ENC[AES256_GCM,data:+dQRrA==,iv:xLA9mQMHHpKSMzieoyYnikUU/ksSKypktm48d2RsOc4=,tag:rcKXh6cnQLWItqwkbHHGYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T12:27:48Z"
    mac: ENC[AES256_GCM,data:PKDT4yGpDlzwiD+8Bup6G72SVaqjIPW3aTJn6MzaHAZo1ffEiE+91khYQkLUh1e2OxjhHZvSUl0q6jtzIgIqw1IEYIS19WZGGAFtKZoswS2JcgIAcSxSoWxttpp3aZzrn2AqWx2zFHwl5BJJ9Gw5jOQQ5MNYR03WyhWuZvJ7Arc=,iv:VEPI+kh6GS4f7T1wGdquDurLUIzVjtat0x9fREXcf6Q=,tag:rqHoVzOOVvAZxr8gR16eGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
