apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: common
type: Opaque
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:oG8zwEKOsDB0CmXl2OUgtIPQaW8utQHUmbTnGEgQaM3koB+nd/5kyZ9wy9sJD4MLrh23HInZKQPJr79pJPADGkkjc3d2zPH3phGck3h4GMmasw==,iv:ZTb/kKeGLmwE9w+MQwZZODp1L0E9G0VUxzyKf+M4YkE=,tag:pYO9DaAMCy14ImTl7/NB4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOFBVWGNBNXFSTUpJWmNt
            SXpzcENqd3REVTVBSkV1RkkrZkp2dTBGNTNVCldDUWtPWC90anhpdENUV1I5cWgy
            L1ZIcVBBVXJQaWVRWERHY0h0eGlNclEKLS0tICtILzYrVlg4TjI0ZStsZ1dQQ3hW
            MkkyTWJsRG9idFFVMG9sdmRhUVdKTDgKzZ1uvLWxE8CZW6A7XbJQEMN015UIoYnh
            fS1I+Rdm5z1qfOmj6qpzoDjDMC+uAgb46KoVH7X66v27sJAEUmxCTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T09:23:33Z"
    mac: ENC[AES256_GCM,data:PxwVTWoesEqZRNg1RgBY7/7Ox0YPq8UIaDRC+T4uiDiba5mRe0yCSDVw6lE2BXSNjhxwzph6QqiYtNQ0+3ALbeI5nTM6a378/l0CvChvYbzW5iAra2w3bAIZAGe0QLhqbVyievsBQ5B6DBlZuzfWV7rLh1ZJkED+ehIDCye/vq8=,iv:tX0sYk5oJSKs4sUQ1elI/8eHL2+fJmtUAt+4FFPhfb8=,tag:Q834UHmwtNFif67Mcpw/mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
