apiVersion: v1
kind: Secret
metadata:
    name: homelab-secrets
    namespace: default
type: Opaque
stringData:
    APP_ENV: ENC[AES256_GCM,data:MlzmLA==,iv:zA1EOLWBJaqbVvRJ1aAxHnok5zCkCH9Pnc44vaLibnM=,tag:8IO1OrmvbdfcwmXHLXAzvA==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:rYL+kw12rqtYzuDDmKwx39I7X6qqg2UjzMzeIRqoMJam8Gn/imfBdQ==,iv:mpBAa3yaFeKDJZGrovUgGPfJnJ9nDaZHXgaKdEiFPoM=,tag:IMpSxaY5+tWphaQtsoeGxQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:H9OfIHFezroGyuV8np9qjE+Z7oxowIusqPpMhjUS8OWcZIEOgzIAWUCP1CLndeFjuC60u5GEnhIID9P+qmDkh36OBDfZLPAqiOZrjXw/L34OlWAWq9jQlx2yG/qCgpmi92ZfGB5ESI4S,iv:e4wBloSZGi1RRINg/WK7VWB+u9Htv3DtF34Djm8AFVs=,tag:1Cq0MASIvVtNi4kk8McnZg==,type:str]
    CORS_ALLOW_ORIGIN: ENC[AES256_GCM,data:qyaWbvjg8s6+ECKB8UGySwfwiGvpgHYFN2zVgTk=,iv:ltJSQU3ikW1d0QGVpZwemVAWyk0JFbVigr4fic0b8KI=,tag:IY+dIj+UVczVVvdildJaQw==,type:str]
    MERCURE_URL: ENC[AES256_GCM,data:3zwkM4D5x9nlhr+uzWF1IjhUtKZTTk3n/jp21mQvdsc=,iv:kO+f5jTb1nIxlvv7Y1zgTlSwUataUSPoFCBqeP/vES4=,tag:GfWs4LwL18OajVK7GAmhGw==,type:str]
    MERCURE_PUBLIC_URL: ENC[AES256_GCM,data:1/MogL2EZyCqoWEZZkpiLRSeKVt7XyW6Qxv22aQ0JsI8lSAbHTDkcImyD72yRqQ=,iv:fAYOJEBjyn9HEmKpl+yxx6yTwouxdn1l0F6af4vFqxk=,tag:5rPPYG2b18drwwp6T2K2WA==,type:str]
    MERCURE_JWT_SECRET: ENC[AES256_GCM,data:FM9Mj8g3J6oAGsFKpuwXGbfYgXfxfMDjUlvI/exCPY6frWGXHECw2A==,iv:YXTjCnwDMNwun3EhQTtlzyPqsE2uWJySmFPSZCDrIKc=,tag:nQVAvUifMkvfP42FFW+9vw==,type:str]
    MESSENGER_TRANSPORT_DSN: ENC[AES256_GCM,data:UkE6z9+27JZKo039EI14Q2BdVK0oWI0AdoIBnBOkqg==,iv:LgdPOYexvlrxQC7Y7blc6lyKD+xLSVvKw/trE+llDVM=,tag:rWt9sEcTuehQrdHTb1qyIA==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:JnGqdZPUKFQXgQiMk7WTam089qTi6KpyogcS5BXlR3fW2jh3VBUENQQ87xUSttIJbM3z,iv:R9ZkOCRQgD2t/xiI5f1qNk7UBqohte4DA2LRHUUAUfk=,tag:UFXpaF7jhQfZKXBtSKOrWg==,type:str]
    TRUSTED_HOSTS: ENC[AES256_GCM,data:SOr5Z7mkJVyITQOYs/K4S62eXDIoquSCPkcxZOM=,iv:udo0TOo3QfKOExWmg/jZH6mdJCy7GWsjsS+e3kUp8Qs=,tag:07kbyZDHM/Rlj3v6BekQbg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UZAFPLqx5g==,iv:JTqWbXyzY5L+uJCtVRP2tMK1fqhIQw4t9TiKx2enIs0=,tag:9AqLr9J/zJRn6dzM5Dz7Ng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:iNk7NahmEQ==,iv:TLEsW8Jj/6jOKhPIAlN5QnJiM5UqbxIsiXtg07kEGgU=,tag:EPPh5o8qzHhTz6mM0WnKbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUnV5UFFiNG9ZbHhlbk13
            SGJZeGhPQk1nMHVBZGdTMysxVlQxMXc5TVQ4ClVVU2ZKWEI2TmU3K0FtVWRaV0RC
            N3hqVFZQN2JxWitUL0lDc0JkZ2twckEKLS0tIDBKcitTM0hQeUlWVHBSM21oY3ps
            ejQwQTlJZC9KTEREWDdDZlV4OXNSR0EKwBKfc7I9KEAbtlqfsKFHLVlGsjqSSpTs
            oTtTbwPvk2XkLBuA6NG0iuELEAEcPLXwROdsZ3ugQmCx8GW9GAdf1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T12:28:07Z"
    mac: ENC[AES256_GCM,data:eufpcNKtWlYxVhyhDJ8Vs1OksyyYJuryiXT07oznqI6JhycSdN6iA+Rcw0iw/Po6eBULh2uwlxrcgpXiryhxgLbb75qAtJSxixQi0jZg9LBaq4CwYIPrgvIGtdWtRywzKLtJMByuy5X7oOfeihMUOp2dS0EgfHMXslP8Dt1s1jw=,iv:jMoZYXsd9eer3FecpojKqJHTic1xZpgMRvbHF+WsZDE=,tag:Np2PMeAC9sNX+rkjSJQt9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
