apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:6nxLMA1oCvUCrr3Sx0gUQiOQaEjlWNyMc/vLuwGXyJf2undvXJWJQA==,iv:TFiLS37vhM0NeYj017JcarTGtHggEAD8+ldFWQO0pxU=,tag:LURerzfOPPIydzQLVez46w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qkt8anezrv89yj8clxg5mhsgps8ygvsndjsn763p7t77eyx3uufs8turrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTVMQUxvMkg2STQxcURs
            WlZ2UWZlL2l4ZTdDTGU4WFNBNi9VVVZnQ2swCi9sUDdOQWhqeDBQanV0MGdyaWk4
            cjNlR094SUpRa0gyL1oxeFpNUVVYd2sKLS0tIE5JYUVZVWZxdmFsL09tTGJiakQr
            aXR5eURPclJrZmFlR21vbThWbWZTR1kKZ63B4eT/kw9CgwywVccLQHStLIztEhfK
            WIHdugEbZngeQQ2oVvb2JHQcvUXj9VUzdy4WtHatSA4wxk4jIaXfcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T05:51:26Z"
    mac: ENC[AES256_GCM,data:CI12s6svWl5srm8Dd07Fan0Y/QER+7toLorPZgvalyt569rWeLVidu77pSMPqD9jeHHiTWd07N+yss2kOc+ggfTYfZNqIc/ri2f9G/mHFLgwMup5m5V4XrLwA3QhxMNALGvjp4c/6A8KB0QNWuyTNsJe8bwxs1fVJ35nItNCdpY=,iv:CGEZG9wN5m0R9c5LYnE41E0zbACBoy6KUeg8VyjWM/w=,tag:JqyxRrlE6r7AiEZy7IPDkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
