---
- name: Ensure container loaded
  community.docker.docker_container:
    name: domus-auth
    image: ghcr.io/paroki/domus/auth:nightly
    state: started
    image_name_mismatch: recreate
    restart_policy: always
    env: "{{ domus_env }}"
    networks:
      - name: "{{ docker_network }}"
