apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:naRDyAOKl22JAl8uLk+AFYtYqXY/hFe1lgEBMP/V8yWaNtnLJ8SnWZnwqn5SOfGCjRagFxqGYBCB7vUd,iv:vbrvxktKLqMMVQkUWpJ1iAFA7kH4i4dXxLFiA7j/ayE=,tag:X86gBUn0AxcKWSLFIuxGGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXBPWFV5dXljOGRtMHNS
            Z1RtWHBsTUNXTlk4ekM5TjQ1SjB4dGtndnhJCmQwaEFyOG5qU1JOMDJkS3RVdkww
            OFMyUlZPdEFhV3hSdDU0UWlrUzl2M00KLS0tIG8rZ1UvaWxBZGQ5UmNtdzRBRHZZ
            ZW9PUkZ6RFYzbXNpMW0yL0ZEcHpHb2MK0Fuu4GHRj21Y1LD2XtXm4SrThuBGhznZ
            zUXpRZbca13wvVN7iqaePNlsUM3mWXu8cme955Mrup5l3u0H0hEXtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T19:12:56Z"
    mac: ENC[AES256_GCM,data:n3eZDTEh8hptX1M2hquavQlYhcWekGEEPjkxmn/+GfQZgkRttKnJS1+ZtV5BaMZfXWzTq6kIMFiKvptvaQTJ4cE1B/hAwqXTCX7BpDx/M+Javz06bjpGbtPq86VPMV/oWcqUdn6TBrsth/ZaVwJd7eP5uvncoVCbEFFQrZRx0dw=,iv:I2YkA7X30gHxLiYH7Oi45K59X/pkfTzy8i8EtMVmT3w=,tag:1Ckd62TpCZ2rCehCEZA44A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
