---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-data
  namespace: default
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: download-data
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.11
    path: /tank/media
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-data
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: download-data
  resources:
    requests:
      storage: 1Mi # Size does not matter
