---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: influxdb
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    auth:
      admin:
        username: "influxdb"
        org: primary
        bucket: primary
      user:
        username: "toni"
        org: olympus
        bucket: olympus
      readuser:
        username: reader
      writeUser:
        username: writer
      existingSecret: influxdb-secrets

    persistence:
      enabled: true
      existingClaim: influxdb-v2

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: &host "influxdb.${SECRET_DOMAIN}"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:influxdb
        hajimari.io/info: InfluxDB
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    metrics:
      enabled: true

    influxdb:
      initdbScripts:
        test.sh: |
          influx bucket create -n mqtt -o olympus
          influx bucket create -n hass -o olympus
          influx bucket create -n openhab -o olympus

      service:
        type: LoadBalancer
        loadBalancerIP: '10.0.0.101'
    backup:
      enabled: true
      cron:
        schedule: 0 16 * * * # 16:00 UTC = 24:00
      uploadProviders:
        aws:
          enabled: true
          accessKeyId: "${AWS_ACCESS_KEY_ID}"
          secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
          bucketName: "s3://s3.itstoni.com/influxdb"
