---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-v2
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-backups
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
