apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
    namespace: database
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:99zgTKgxRlvcBM2StQu6ag==,iv:U/8Pk2G5scTqONvrroSuExmT/ee++W935V0iKbr5zKg=,tag:pBv5KnrYc8M79no53Vjieg==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:BK8JuXNzgLWa4PE0OmBsoWNPEr31wpchdDl+1N7pVPc=,iv:479Lx9QmcxoMxvoPUEJxFUYvr5u8U+IB2dOlL/DzJ+E=,tag:1P5D4BGmI2NhwwxZEuICjg==,type:str]
    region: ENC[AES256_GCM,data:wVo2hmDSwc/2,iv:cI7Gx2eIWv3Ne1vW+FtuT2iS0fvu5/NMBgB9THoqG1I=,tag:DDuxRRMYQDXR1HEtguzqdA==,type:str]
    admin-user-password: ENC[AES256_GCM,data:CrmTyoegw76J2vU=,iv:EuuGm1Ed4R2oaSQfGByZJi96RKZXR7dR7gujWUf2uBg=,tag:KnQKiaqrZM0nM2Rc3OHHtg==,type:str]
    admin-user-token: ENC[AES256_GCM,data:1DxNi0BqGAhPUukDSNaN7MwQr831VN7kchrF+pJiKE78IRC9QBRdZRrea1OkYJFfr3kuSfzVjMfaLVRH0EUEO5w7T0WBLCSk+riJLpXdcJrLa/812oCvOw==,iv:wc/0fZC5ySkrzupMsCJQok1dra2tIC2/AQgrKqjZuU8=,tag:CJk1dDyRZNooQMOZWABO0A==,type:str]
    user-password: ENC[AES256_GCM,data:engIMT8QTfikCAs=,iv:tY/ANXgUcDgA9RUzOpU9gLXnrokw6f7cT9vmerCdDcQ=,tag:lfQ8rUy1EDpiYYD1XunkUA==,type:str]
    read-user-password: ENC[AES256_GCM,data:TaKZhlXO6Nr79dA=,iv:g5Oh42I+PSrTMiYnsSd3JaN1UrgjPtaOa7jYEDMnCDU=,tag:4mfMPsXczyZzRVcwyeelkg==,type:str]
    write-user-password: ENC[AES256_GCM,data:jP/X8c/Duebdj6A=,iv:OB5ClFvhjytsxtyQSLqCVNplnTqSJSOs/+TPb9kz4O0=,tag:2fV2YLMpeloh3kOchN3pTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VTBOWkRFZWF6ay9TNVNR
            dnQ1UzBYK3RlZVF2eEhFUEJXdHlNTG9VSFd3Ci9OaTM0K2lOTHJxQkU1enpta0p0
            aUx5ejZMUlAyUUVxTFVzNFhlWWJ2Z1kKLS0tIHloY0J0NTJPMnYwdlNTNVpiS1Jj
            NkVSR3Z2NW9ndy9PdUtpMU1yRDNTZDQKfK4hj2LNbkPg00gOuFAaXICWKFO/jODn
            ojIKnzBKE9sW8ho5bLLZXbkA47/F/rw9UVLyYXawfQdnZV7gF/aNzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T10:17:24Z"
    mac: ENC[AES256_GCM,data:BTLaOvvqJcAnPrxmw/kIA3y0Xoqy9koyqH9bbwN1VrergrfbzgJwMEeQA/xoeBmsgdQULBMkpuXCwwngKD4L4LfqGrIrA182UdPP+M3s28mcvGoVhT+uU0YzHp/O1Y1Y2JwOiQcdP0OWy0+Px+70k8JgTs8C67Rm2F0uh4Mg4c0=,iv:z8dwy2sAMUwvdrittIodGu9XKhCLjTPvyUX0LC8UPvM=,tag:lRwASMmzVDr9pQ8K4p+ENg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
