---
kubernetes:
  children:
    master:
      hosts:
        hera:
          ansible_host: 10.0.0.3
    worker:
      hosts:
        mars:
          ansible_host: 10.0.0.4
        iris:
          ansible_host: 10.0.0.5
