apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: default
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:4EMDzJJ8FrmwXCRvhYycs/6ojf22VumUjUyX4q9xk8d4ZcJMLU4644GSkzF3nZyUmApH80FgI15m3o5aTNezYA==,iv:6DDTDxTy1L9Y9lkASZ0S7Jj2bq8tpluszJ1xIE+iwOk=,tag:WvCauvmHYBmSosE39l7nsw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:xnUK8xmZF4sBzSg=,iv:sz1G0H0po1/4izCmXsEsPoPg2Uet1ADFsG+fKK1DGOI=,tag:7qPD4aY5xWZBt9hEyCktOw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:d/AUAH+fzPRDZ5krQZI=,iv:7FtsaX1YDdhd7vsw6tzi7yxl7GuYwW0D1/mTmDvVhpY=,tag:2dpAawUWz+BImFgeE4z/SA==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:3AgfWRvqNVGVR0oQEUpEedgbIQWdhflgtuKBTQY6Ed0YGHZSRNAiZLKwPF/wS5Co8lM/gEEZjEvFAGxE7vYS5g==,iv:bDh+bToU3aYhHrelOnxvIgePXmqsBAPqn7k5krj94mU=,tag:qTPVTimqHjBbgli2pPi9ug==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:k/nMrqg=,iv:OeUKdAv02kk6vlEYCKv4MtBDhK/Kz3j+CW9ugoxgbNc=,tag:zSecYc0bU7NzNH+h/aABWA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:AokYcJ4=,iv:bKteyXKrRppmxEq+C8h0e+BCLX9B6iGyfbpstlRE9ok=,tag:eOFd6Pr4/WPIW3qqtN/7HQ==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:Se+gheXF5siPsoWyjhmOWgPXGdvbOf/a9hv9FCNohYhwaedmvfmxgrUDCVOvuvPZzfYGyLM5nsR6L5T7VG09HQ==,iv:LVnfvWog9Ih3jsvtwQVtjJwiuVuqKTJwb211AxEAxgo=,tag:x1MyoYSV1aHS8GFklfui3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVGJpdHl3emZyS0x2TGUx
            NFBDMFV3YTVqT0d0OHVSTExZUmQ0cmR6L0hrClBITVF5LzhORU9uckQ1T3JnU0FJ
            UXJ2TGZ6Yi81TWFMRGEvV2RIclZ4eDAKLS0tIDFvWk4zWnRpR1d4R0trN2dEOWdv
            WUlhTTZZQ3pmdG5waHJtdWwvMy9WckUK1vLTXjIDwjfEI0bfjX9OqFaZ1+Gu6GXj
            Jybb0fPtZznLX59hTy5WAv7MmtMVWSq3IGpHqigyPq4qY6RnW0kT0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T02:06:24Z"
    mac: ENC[AES256_GCM,data:45UAKFQ8OUblJMWLXjP7j4uy0nics4GJAJHXDZWqIVOgXu0KZTSiTt/9ZfNE+HDmUMSAbj8bZR3x9DbGN+52UJTu/PX9IMUcfxU0FHToklfWXkRm08QB7U7zqB647alZ2mS3p5C4D0KCLoKop6QnayGAYLOYmvVDoYYZuHOoVqc=,iv:L/M14k0VOltf4suSs3cs3oEm/iAp1C0q+ur11V/7wq0=,tag:mXaiB8o301mWBhjKQ9YlyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
