apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    tunnel: ENC[AES256_GCM,data:HasZ2jxO5ZcB7PypU4H/5gnEKYlvfTwT2pQhGWbp0s9d2TJ/p7IpbS7BQB1YI5hjE2+StK430KBMdwnNryYNbs8XnhpmQvMwFA58FJFjX0FWD71u+8rgrSv4telbeQ0IP5DFg9E8bUT81xXyMjZyeugo0YLXmAS9zPe4+llBppMdtGEqBn9waZeIFFWAnmu09ltnymtRNfiOFMPWpLT8qbBXCEhh9a5BfdCVCv0h69w=,iv:6BICKdsJkH+J9AnVGjT1/bSxWCAICD5Rsby39C6mI7Q=,tag:VYqerfE5ANH4LJGm0BBuIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEtEYzVhODdxdDhSRTFN
            WXE3UWx1eUpnbHdZb25td0c4emtBSisrZ1U4Ci9nUjNyeitjZE1rUWNPRTVJZUJt
            dmhlQXRoK1BXZmo2cDF1OFIzMHd6ZkkKLS0tIEI2RTdrREY1cUpTajNBckwrQ3hv
            cXRuRE03aFMrM2ZBQVVPRDRXUHZPazAKVcttirwYIW20XGipuRqdwZlsKI9fyCNs
            JXDLN34K8boXH3rt4mV/quhsIT0oRugqf0tuze8g7FmzasijV1/TWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T07:10:17Z"
    mac: ENC[AES256_GCM,data:vlw3Lb7ofhY1bbGPJZzpKBxcbDVnfLG4YefH8/kCCJg65KA5A6jaxeHUUWljTVbX+iIgQu2wDkou+fxOCq+MnZL44954nn/VxzUEguOMcpM07YUoNgLRD5XBIs/3EkV7VQ2BYBHYS1Lf72u5tzFpjSYYNStBt1g9vNCT9Y97tCA=,iv:oB7yAKgn+K8gXITPeHdti5zxQ3ezx98AULBkm/mbi8Q=,tag:PSx65SwH+p62vZzrlmyj+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
