apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fiq7LnCr7fquAJTob96i,iv:5YmdewV2yFLEpU3sIXuhdmW8VkiuHyKX1nGKie4PxEs=,tag:/wcbwnxh6CXCucVrmCHihA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:s6ZsF9X/dVSQmKs=,iv:B1HtjeQRKWRytCDs8Gt5BoWJOwePvIlNcJPRfvdac3o=,tag:y/7afmnjnLIZ3phBt8E0Vw==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:SuRDIrxJxf1n,iv:fOJ/d2yh9k/NMdKX7csN5L87cDvol8K3Ly/ImxDSBEs=,tag:bsKWrNMvYXVkeMgI+oNC8Q==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:+h+YhHIcDzUQ3DW7S/GZ750SnNYq3KK/2PyQ,iv:IVBJecYIDw0vl+jl+HHPt8lQS+OmdiX3wpcDp+pWLaA=,tag:cQBy0fB2mJyuuOtF1Zy20Q==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Brox4tpOmMdXRZs=,iv:OVYeKaO4ome0KqT0+iXmN3iMT1icDnsWPySCB1QN7bI=,tag:INZiCNAXHG5Mmvld0dQ3XQ==,type:str]
    EMQX_IPV4_ADDR: ENC[AES256_GCM,data:bALBNE4Y+G4qmWax,iv:lRPkExShjKvGNpZRqFmi9L6+j+/wvuhGhp+BFn2uCRw=,tag:/eljq9ovilzJOynG5GZMBQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9/GGkYMILZaCOmzMd73oClwakcY=,iv:vlTOUUN4FKLpg3TLedBI3LkF5Q1jyngB49f0gf/p6KY=,tag:sNxNQfo2FuXesVWcdOFzBA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4lbfhbMBDz1/v6mohzCXnw/hHjRx1ski+rS4VhYtkq3Z/jGr,iv:x9mA+Wg40IlT4qyxhRMAzoYjhbdMVSHs8WEzBFlF4kM=,tag:ySyxuHedQkfeGujpydcb1Q==,type:str]
    tunnel.json: ENC[AES256_GCM,data:L0ndfpkmxEypWOjTIJPFQIwqSC5xDAeuhEqSVny/1OZtOPAdpb6Q2ftnjkQkDgQzgV9U7WULjpSEkXRSnOsWvYh1TWcxID+S1s9H3coSYY4xlYgGiNouzlxbaDTHlvKmrSQi1cFs3oSSgBuHHl/79uAWoGY9wmHxD7p0vKzx5s/rzKiOCALR1KxNQuHE936knzAZRA9WCOchFy5tRASO19JKb+fciH89UP4VT3HgI8g=,iv:6309t7uH7F+F38Jk8sH1hhkRpnctRnoMTMKeDBmfM1Q=,tag:ChHbWcMxY51CsMQ6pr/eXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T06:45:27Z"
    mac: ENC[AES256_GCM,data:ldSyepVE2I0sQnvzAAPdm1PBjXr/OtZGnEnwhKKw4lllV5NM0pBeHAwkD+4DUEfveUfrefH58NwQW3dfBqIr6ndKr5I6UUo23OXt/p/SV4ZKosr3eg5ixo5pB7pEzrPXWpqL/H1skH0169s2q5Mlc1N56+IyOy00xHH5jYHZ5h0=,iv:PPaP/oDxrxo2ggFmC/EOYlZ85/WGpsfOlbT5bu8E40c=,tag:7Adj91ubhPOuj1L7n2CUJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
