apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JACqAye5cd8/6gs=,iv:acfvc+jCnKEoIfNcgz+L1AC7c+6cFWl0o6/um+kW8ws=,tag:pX32DrCUg7h9bGdkbY+18g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+I/jYcyiQCo6gsLRyVY=,iv:WGw0rY7aYS1D2r75pAln67Lsll95PSL0NLxuoWTMPRA=,tag:Wtze4fHgTLDrsYytMstb3w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9ZbgrD/ga+iwc69XQ8ykKkQaeekTbDd8ec6aNK0QoXcU0C+4,iv:WzIE4zDtUOihzyIUNR1h6gIUxksUr/JMHWEeIND9xr8=,tag:Lt5Li5GgPu7G5sRzxo7eQA==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:rAw6gWJkBFZplnfvsfM=,iv:nnRKqBzzJ913ZCEfwEGPb1ZaF+9Gd5rnlPTstW1X6Rg=,tag:QtjedWPnqUDcgX4dJ50xXQ==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:5OhQr1UykO1zbgGafsaWAnBt5fzMZ5AH7qQYCDkVCIt9g3Fs+e6cG98=,iv:VgcEYbo7hOY6O3J5QphbcClxwQHgijePQTuG4Dpqw4Y=,tag:xbhBVfiz9uN9yqb1gfT0uA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:jPyFAMb2fl+inAPD155RPRDmtcy94XlY1Dm5VLHz,iv:wRtugcfKH+qlK5KLuskiHAFnJ1o6v9uOZg8yfvY77w4=,tag:Fl6pt5F+1TwoevK/8Nh5+g==,type:str]
    BW_HOST: ENC[AES256_GCM,data:vNV4/HCU6AEQEEpwLQ==,iv:uB6wtybVQ5IyiGWCxGlUn0ZpHmn4UdnWVHNehmdtU5U=,tag:8cWj3xV/v1M+Hem1Da/3zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmptTUhJVU5YMXp1YjJE
            bHJsc2NvZ0oycFdPLzRSM3UrN1JOQzFmNEVrCjIxN2RPK1YreUxqSDJmREpDaXk2
            YlJLZ1hLc3A4N0UyUnpEdmRoWkV5ejQKLS0tIGVqTFF3a2o2WDhpak5mbGovMlNW
            UzR4b095ZHNhbUNTcURTSGFQK2Y4VkEKzbIHezmM+P09nL6dxZd3cizfMm84oV59
            EMnP8SJlaUiHYLbvxrNmrMw33mUzNuldMHH2K293hL28fmFZl0fbkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T15:13:10Z"
    mac: ENC[AES256_GCM,data:uD5wY6dUUcJkMvAGx0lR6VKikRlGtQB0Pb1GPaWa/Lkfe93sLG2m7WFGzNf1PxgtVcs3BtPIgSVjubhkQHg5lVuFlkv0JfDIqA+8ZTTHo19IrtqSwNPYBKHN0xHUnJHnhYHjN2bEXiaND5Qr17MQMHGyhks/ZKGlJtnAaODWJgg=,iv:g4dpg1iFyZ/E/4DBegBH/5aT/LP3PHqneEKjcI6lmdc=,tag:KhY0jCYj/lPD46/HTh5+hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
