apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FOyW5MZg+RDBZ+U=,iv:y/BBx3jeY8mGno4TZm24YrRAlq1nkYaKHJ7dJH9Ufyg=,tag:U91bB9VUSNuLsubQzaJSVA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:G8a5eHp8pBy3EnYWKRU=,iv:tyUCgOXvHj7jdZAmnPTCPwDq+qlPX1YD73u2f8lCyCE=,tag:qKJk8oUfMb90ky4eL377ow==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:i1YzmlWVrmihDeVEnhJc0+FjC1pWul+19r5snRUKZ3biEdim,iv:7uhw4zJzSpZkjaREJxFFn2tUkfYekVH+zHHYsML7c5k=,tag:Gx1pFyw89n5ogLuzANP6pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Vnp2NDRVVGpLS2dxVE9h
            a1dDeHZOYktVczVNWGNqcEsxODhOWlFGc25ZCnF5dFRMMkRSWFpTczlhUDNHei9h
            UkRwUkVERkZiYWY5S0YrUHBLNWJTaWsKLS0tIEV0YUU5UzcvUEN4ekJ1UytEV0NW
            VXdmMG9LWlhHTkQ0WjFtR3g2aXdmVlkKH+Hl2UyJ0NAJLkMrAVgZqRCkAWex5il3
            tkSQaoaKaqbOTq6Y+Skd0ZR4I1pjvrHWWqMpDEO69YobzUbSn60wnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T13:13:58Z"
    mac: ENC[AES256_GCM,data:cK/oTVIYotFnL357YmISAbGLclaaiNlYR5h//tSEdMc30M7YDJHQXBACwI53sLbGngoVmLKBTdTUr+O7F4BfQfJzH+yRdbvU7Gb4i5raX5JTkahBqb2SCfY4vxn0OyClv8/OemtUs+2CDNzpuM917tmuBrmYlDnRehGC4PpqjpE=,iv:FbLBnkabhXDrySffLFmxhvA+Pv3gc8WQtpSDhq2kcD8=,tag:mjR3aHNHaXMVtvH6Mk7eXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
