apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:u/XIJMajPbNnI8U=,iv:iNs/wcxmJly7MV+hLmcontFnZlIZwbBiKIFSNQ0Wax4=,tag:3AwCiWKQ3glaNBaz6VYxXA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T19:12:56Z"
    mac: ENC[AES256_GCM,data:/CO1SRiy1AvwZtlL3HBdP/g6UswhP+hbLQBrxmbD735KjRkg5+3fIZB3G2WCEAPGo/v4wq6eOeCdMqrgI66I4qeVLty/iqfN1+jr9DvldWP0F0rziJt08OiKoyivTRZyVS7IF/JBFXHQ6CMD/tgl28xfDzwocF2Nnhsil8K+ATs=,iv:/d4Tkfcoj5FKcCIxD0U/dd0mhPtx68cQpL1oaQ3+wfg=,tag:P4ZHLUf1gsdxhsfWPqOTXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
