---
- name: Create librenms directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /opt/librenms
    - /opt/librenms/db
    - /opt/librenms/data

- name: Deploy librenms containers
  community.docker.docker_compose_v2:
    project_name: librenms
    definition:
      services:
        db:
          image: mariadb:10.11
          container_name: librenms_db
          command:
            - mysqld
            - --innodb-file-per-table=1
            - --lower-case-table-names=1
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          volumes:
            - /opt/librenms/db:/var/lib/mysql
          environment:
            TZ: UTC
            MARIADB_DATABASE: librenms
            MARIADB_USER: librenms
            MARIADB_PASSWORD: "{{ mysql_pass }}"
            MARIADB_ROOT_PASSWORD: "{{ mysql_root_pass }}"
          restart: always

        redis:
          image: redis:7-alpine
          container_name: librenms_redis
          restart: always

        librenms:
          image: librenms/librenms:latest
          container_name: librenms
          hostname: librenms
          ports:
            - "8000:8000"
          volumes:
            - /opt/librenms/data:/data
          depends_on:
            - db
            - redis
          environment:
            TZ: UTC
            PUID: 1000
            PGID: 1000
            DB_HOST: db
            DB_NAME: librenms
            DB_USER: librenms
            DB_PASSWORD: "{{ mysql_pass }}"
            REDIS_HOST: redis
          restart: always
