---
- name: Ensure librenms service configured
  when: librenms
  block:
    - name: Ensure librenms database exists
      community.mysql.mysql_db:
        login_host: "127.0.0.1"
        login_user: toni
        login_password: "{{ mysql_pass }}"
        name: "{{ librenms_db_name }}"
        state: present
      register: db_check
      until: db_check is succeeded
      retries: 10
      delay: 5

    - name: Ensure librenms user exists
      community.mysql.mysql_user:
        login_host: "127.0.0.1"
        login_user: toni
        login_password: "{{ mysql_pass }}"
        name: "{{ librenms_db_user }}"
        password: "{{ librenms_db_pass }}"
        host: "%"
        priv: "{{ librenms_db_name }}.*:ALL"
        state: present

    - name: Create librenms directory
      ansible.builtin.file:
        path: /srv/librenms
        state: directory
        mode: "0755"

    - name: Deploy librenms container
      community.docker.docker_container:
        name: librenms
        image: librenms/librenms:26.4.1
        state: started
        restart_policy: always
        env:
          DB_HOST: "{{ librenms_db_host }}"
          DB_NAME: "{{ librenms_db_name }}"
          DB_USER: "{{ librenms_db_user }}"
          DB_PASSWORD: "{{ librenms_db_pass }}"
          PUID: "1000"
          PGID: "1000"
          TZ: "Asia/Makassar"
        volumes:
          - /srv/librenms:/data
        networks:
          - name: "{{ docker_network }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.librenms.entrypoints: websecure
          traefik.http.routers.librenms.rule: "Host(`librenms.{{ traefik_domain }}`)"
          traefik.http.services.librenms.loadbalancer.server.port: "8000"
          dockerdns.pihole.cname.domain: "librenms.{{ traefik_domain }}"
          dockerdns.pihole.cname.target: "{{ full_hostname }}"

