---
- name: Ensure mosquitto tasks included
  ansible.builtin.include_tasks:
    file: mosquitto.yml
    apply:
      tags: mosquitto
  tags: mosquitto

- name: Ensure home assistant service configured
  ansible.builtin.include_tasks:
    file: hass.yml
    apply:
      tags: hass
  tags: hass
