---
- name: Ensure mosquitto tasks included
  ansible.builtin.include_tasks:
    file: mosquitto.yml
    apply:
      tags: mosquitto
  tags: mosquitto

- name: Ensure authentik tasks included
  ansible.builtin.include_tasks:
    file: authentik.yml
    apply:
      tags: authentik
  tags: authentik

# - name: Ensure authelia tasks included
#   ansible.builtin.include_tasks:
#    file: authelia.yml
#    apply:
#      tags: authelia
#  tags: authelia

- name: Ensure home assistant service configured
  ansible.builtin.include_tasks:
    file: hass.yml
    apply:
      tags: hass
  tags: hass
