---
- name: Ensure ssh configured
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags: ssh
  tags: ssh

- name: Ensure gpg keys imported
  ansible.builtin.include_tasks:
    file: gpg.yml
    apply:
      tags: gpg
  tags: gpg
  with_items: "{{ gpg_keys }}"
  when: not ansible_check_mode

- name: Ensure pass configured
  ansible.builtin.include_tasks:
    file: pass.yml
    apply:
      tags: pass
  tags: pass

- name: Ensure chezmoi configured
  ansible.builtin.include_tasks:
    file: chezmoi.yml
    apply:
      tags: chezmoi
  tags: chezmoi
