apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secrets
    namespace: filesystem
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JmHYSvdNUzC/AiNyLZ2e4w==,iv:a/7bYGanBgQe6eiN/pscDF84GQ42ykYZ46WcpxfQX2U=,tag:bU/3Dfs7MRgQRoYdSk8zOQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+vlf6LbB1nFCmt6UjqewLiLsNh7zQZ30Ndqm3OsJIOU=,iv:cSuoxwWzoB9ZZUKxMlxkaAODLmejOXvW1gTnpob1+xQ=,tag:8Qe1tNPqIG8n+XpV/iSd8Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:aD/WZNAigpJnzJRWaEEdKowrk+fce/bsT5aO8Lf0JcC4fOzUZPGb,iv:0UD9c5ucqn6B5zQpuqJ7AwZmngaU6JdZTqWkSH4aquU=,tag:+PianaW9oK+5vpKXecLxvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVmJJMGEweDZUT3FSTm5o
            NFRpZi9MOEdZU1VsQXFOUVJBQzVrOVpTM1VJClBYam1tRkVOc09pYjdMQkdtUzJi
            Qll6ZTVLdXA0S0NUdE54OU05NTJ5d28KLS0tIDdoeW1JRHU3WkF4L201eVBRaWpW
            ZGExY1pwRWRyVWlzN2QvbHJEUjgrOFkK6LlIaetz25HlZGG6HrOZKfkdzzkHOjhr
            T5ND65XcuGIy231pakVePW97bG9WzQKvZNvtIUqW/cul8pGDd8EXXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T14:22:05Z"
    mac: ENC[AES256_GCM,data:Rja09diHNsMmHHjZFk2syxlN2q0hAnxwYAydJuBDrBiocMshZjPIjc4tIRvYeLZ5OVmssE57JEmRqwNG9w0A0tzrbwE3dxyuagqso4MhtUX5UD6zAFS5mTz/4juHwI49uKqOxso0YuzpP/etQfTiG2o59KgoMN3abRiQuokS1N0=,iv:/F4bD4yrGh3sIjig32vxPrkEjcb/CdhgPo4MjjOWE98=,tag:m8OZlIElJNQaSjXCljm7uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
