apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secrets
    namespace: filesystem
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ixa7E1bT,iv:u/Ex1dOqEIG3Up1kSstKoqsiMLu/iseEaapkCpAloQ8=,tag:Xdt/mYbAfPvl4bnVQTBUjw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ejJP09No,iv:Qww4UAi1UY44qnbL8gXBYjzbEn0f5fmBLMFFLP/TShE=,tag:gxHGjrhA0mEBKfUi7CWW6Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:MZGR2AxDjAhPCgC5cTsqG0xYETYd2tBG7wdt+WMnoA==,iv:RZYBZCEf9fu8/fLeA0zf5pZKbNn7OwPb+ZACLN1UJ9o=,tag:OtCQefoa3g9oyLUPMGmFhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVmJJMGEweDZUT3FSTm5o
            NFRpZi9MOEdZU1VsQXFOUVJBQzVrOVpTM1VJClBYam1tRkVOc09pYjdMQkdtUzJi
            Qll6ZTVLdXA0S0NUdE54OU05NTJ5d28KLS0tIDdoeW1JRHU3WkF4L201eVBRaWpW
            ZGExY1pwRWRyVWlzN2QvbHJEUjgrOFkK6LlIaetz25HlZGG6HrOZKfkdzzkHOjhr
            T5ND65XcuGIy231pakVePW97bG9WzQKvZNvtIUqW/cul8pGDd8EXXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T13:41:08Z"
    mac: ENC[AES256_GCM,data:xj+0Ul8nLRdtCzE6cFadW7s4s9mfEEi3cWGLKfHRuyTt7B5q16EgbgpmbtoswmVxsbV6HULcCdnCG7mcH7ij3WjhwQE0RQxXX+dW4me2qToVvPPhxAMVzI7OrkeG0uepL+LjtRu9U9/pHKxmzIKVriMNXg078/IrPjb+EYglGeo=,iv:Mp/jnt15FAOfdE7h5s3ruR2Ks5hi/t++so2F11vAauA=,tag:Z9SPt7fEwIR7LyVstnhhXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
