---
emqx_version: "https://www.emqx.com/en/downloads/broker/5.0.21/emqx-5.0.21-ubuntu22.04-amd64.deb"
emqx_users: []
nfs_exports: []
zfs: []
zfs_pools: []
zfs_pool_options:
  - -o ashift=12
  - -o autotrim=on
  - -O acltype=posixacl
  - -O xattr=sa
  - -O dnodesize=auto
  - -O compression=lz4
  - -O normalization=formD
  - -O relatime=on
  - -O canmount=off
