---
- name: Ensure service facts gathered
  ansible.builtin.service_facts:
  tags: always

- name: Ensure upgrade tasks executed
  ansible.builtin.include_tasks:
    file: upgrade.yml
    apply:
      tags: upgrade
  tags: upgrade

- name: Ensure base tasks executed
  ansible.builtin.include_tasks:
    file: base.yml
    apply:
      tags: base
  tags: base

- name: Ensure homelab user configured
  ansible.builtin.include_tasks:
    file: homelab-user.yml
    apply:
      tags: homelab-user
  tags: homelab-user

- name: Ensure fish tasks executed
  ansible.builtin.include_tasks:
    file: fish.yml
    apply:
      tags: fish
  tags: fish

- name: Ensure zfs tasks executed
  ansible.builtin.include_tasks:
    file: zfs.yml
    apply:
      tags: zfs
  tags: zfs

- name: Ensure nfs tasks executed
  ansible.builtin.include_tasks:
    file: nfs.yml
    apply:
      tags: nfs
  tags: nfs

- name: Ensure wakeonlan tasks executed
  ansible.builtin.include_tasks:
    file: wakeonlan.yml
    apply:
      tags: wakeonlan
  tags: wakeonlan
  when: "'wakeonlan' in group_names"

# - name: Ensure emqx cluster configured
#   ansible.builtin.include_tasks:
#     file: emqx.yml
#     apply:
#       tags: emqx
#   tags: emqx
#   when: "'emqx' in group_names"

- name: Ensure certbot configured
  ansible.builtin.include_tasks:
    file: certbot.yml
    apply:
      tags: certbot
  tags: certbot
  when: configure_certbot

- name: Ensure prometheus installed
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      tags: node_exporter
  tags: node_exporter
  when: "'node_exporter' in group_names"
  vars:
    # renovate: datasource=github-releases depName=prometheus/node_exporter
    node_exporter_version: 1.5.0
    node_exporter_system_user: 'prometheus'
    node_exporter_system_group: 'prometheus'

- name: Ensure squid installed and configured
  ansible.builtin.include_tasks:
    file: proxy.yml
    apply:
      tags: proxy
  tags: proxy
  when: install_squid

- name: Ensure nvidia gpu installed and configured
  ansible.builtin.include_tasks:
    file: nvidia.yml
    apply:
      tags: nvidia
  tags: nvidia
  when: install_nvidia

- name: Ensure ntp server configured
  ansible.builtin.include_role:
    name: geerlingguy.ntp
    apply:
      tags: ntp
  tags: ntp
  when: install_ntp
