---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_SUPER_USER: "{{ .postgres_username }}"
        POSTGRES_SUPER_PASS: "{{ .postgres_password }}"
        MINIO_ROOT_USER: "{{ .minio_root_user }}"
        MINIO_ROOT_PASSWORD: "{{ .minio_root_password }}"
  refreshInterval: 15m
  data:
    - secretKey: postgres_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 96626829-03ce-43e5-8787-b1ba0120cbe6
        property: username
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 96626829-03ce-43e5-8787-b1ba0120cbe6
        property: password
    - secretKey: minio_root_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7666f1f0-9412-42c7-9f5f-b1bc00593d28
        property: username
    - secretKey: minio_root_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7666f1f0-9412-42c7-9f5f-b1bc00593d28
        property: password

