---
- name: Ensure postgres tasks included
  ansible.builtin.include_tasks:
    file: postgres.yml
    apply:
      tags: postgres
  tags: postgres

- name: Ensure redis tasks included
  ansible.builtin.include_tasks:
    file: redis.yml
    apply:
      tags: redis
  tags: redis

- name: Ensure minio task included
  ansible.builtin.include_tasks:
    file: minio.yml
    apply:
      tags: minio
  tags: minio
