---
- name: Ensure minio facts configured
  ansible.builtin.set_fact:
    minio: "{{ true if 'minio' in group_names else false }}"

- name: Ensure minio installed and configured
  when: minio
  block:
    - name: Ensure minio container configured
      community.docker.docker_container:
        name: minio
        image: "quay.io/minio/minio:{{ minio_version }}"
        state: started
        env:
          MINIO_ROOT_USER: "{{ minio_user }}"
          MINIO_ROOT_PASSWORD: "{{ minio_pass }}"
          MINIO_DEFAULT_BUCKETS: "homelab"
          MINIO_BROWSER_REDIRECT_URL: https://minio.itstoni.com
          MINIO_API_CORS_ALLOW_ORIGIN: "*"

        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "/srv/minio/data:/data"
        ports:
          - 9000
          - 9001
        command:
          - server
          - /data
          - --console-address
          - :9001
        labels:
          traefik.enable: "true"
          # minio admin:
          traefik.http.routers.minio.entrypoints: websecure
          traefik.http.routers.minio.service: minio
          traefik.http.routers.minio.rule: "Host(`minio.{{ traefik_domain }}`)"
          traefik.http.services.minio.loadbalancer.server.port: "9001"
          # minio s3 service:
          traefik.http.routers.s3.entrypoints: websecure
          traefik.http.routers.s3.service: s3
          traefik.http.routers.s3.rule: "Host(`s3.{{ traefik_domain }}`)"
          traefik.http.services.s3.loadbalancer.server.port: "9000"
          dockerdns.pihole.cname.domain: "s3.{{ traefik_domain }}"
          dockerdns.pihole.cname.target: "{{ full_hostname }}"
