apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: database
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mjsf78IOY3oTWMUeIWav0Q==,iv:wBDoKjNifR9r+bZL7jMo6xgaxalKLbKPSQrvd+fUpNs=,tag:0bVKCyuB2/B+AQMSah8fdw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TLEU0+3htjGc5vZAY4rWdx2lZqYDPOTcT5yHDC+H7h8=,iv:6Q0LgAyBVmjxTZJymRZErkcD9nrkNN2LZYgvNlKlBcw=,tag:0MSfvmwYpBFYWAe0FLWMzA==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:uFJrguYA,iv:SyDVsLfD80i/IBnGMk1YnQ0+LV1dEz/GtX3rf3jmun8=,tag:nb449t9yTwZrmzJgp7cgYw==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:odTpWpgNQhQ2Qte+fJL5kt7KBWIuMg==,iv:2ActgRDj6A2RTJn8E5lQRG9oPfAlPeyNbTdQ3Z0oIBM=,tag:yPrjXp0LYlGFDVxtUwoCWA==,type:str]
    BUCKET_REGION: ENC[AES256_GCM,data:HY0gEIgPgqJW,iv:pitkeSGD2AdIzb2bOPU11b+67eU4fubTzh/FLSVNPZg=,tag:pM0Hkp2ZnXG0gp1z6Z3MNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T02:06:59Z"
    mac: ENC[AES256_GCM,data:krKVxNGQdKaWekULEWPaWsabEv8xm21igjgc4ngBQzBzvhbaVceBPo7XwVGyTVnikxis0ibogb0GjF9I0qiibtD7mx7I97rKmJhiAbtSWCwhCI2kgl4G59GJNI3bXmJBxNi3W1h3hqJXslW8AqZq8blRePjxR3jZ58dCWfhQpeg=,iv:KqmR2APxf5k9M94t9UOMS33dakSwZVd98tWapMhdExE=,tag:fhXdXJ/VFTwEQE7ZObQIjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
