apiVersion: v1
kind: Secret
metadata:
    name: thanos
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:FdQwfrYnaIkwf576yHVr5w==,iv:k2RZRmugUuMwXzHgiqN0/Uvd0VkKkoVtv7lIVpvq8zk=,tag:DH/G7yRmXgTawcJdy54eOg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:61hD6+iCtwBqyE/9boypVAspLmqNN2RwplAyOqLXyk8=,iv:/53D6SgosUr4OdmAd/dTIXzfrRPhCa7UO/LJWVXE05w=,tag:Mv6RUHNJbvQSv15ll/XKgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c0szSG15Njh2aVgwMFho
            SnROa0l6MG5hcEw2eUttcXk0UmFiaGtvOUdvCllTV3QrYm1zKzF2ekNRWENsdzdn
            MGJkSmJDWHVWTWk1UHcxNCtrbEttZlUKLS0tIE9tUDJFSjB1UUZMMHBCYisrQmpv
            Q0tybndyTUF6ZmEyQXhrUUlkZ2w2NEkKc16rJ3KiWyfLnGggWO82PBMhpyY4AEvX
            bQXgzYEss2vkAefkhiLoKNv+wtglX+MJbButyHPTAmHLLXJJ77cw/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T13:43:43Z"
    mac: ENC[AES256_GCM,data:WGZIvIa//0nK0UHDPnevvtZw7/kqCgK8gxVIm/E4tfrlznwyg5tHkTgAeHI7gQoQKlrSbEGeiasK5qBBqfkyuoGWAhCf2tQkCf98Lkh+ueAUOD0HK6BTm65RVNwbcqKrFsw+ngMlsE/IPHA90rGN0uihSOA2JMsFwqQkxuCaisY=,iv:eScWpWliuytvcRvM8SGi0OKPdyLvPun/AmJCXxZDQMc=,tag:FJNKA7mNEx1R4YY9mTbn7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
