apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Xdun/snXsctb3gZLC6SqEL6lUBH5s6u3Mcblef6XIDeL2s90,iv:I4QxV22iU7gKzk4fbhkaPv07bGG4fAYdt1xC/uTNFR0=,tag:d51uRCkV4QkKNWGiHDWstw==,type:str]
    credentials.json: ENC[AES256_GCM,data:965Athjqt/CsjPXhrUupmrlX+P4L3tzSQfTtHdEnvC1MmJ/aIQNqmZ/Ivo8+ImhkviQf8L8mZUR4+d8ALUUQfJ1AEqi7NiS0xP6C+t6mqPTCV9KvZY7hZg9L7yYL9/0+3Q74HbNehfO9q6tpITG2P9lT4mB700eSxnFdr09M6+W/qG2JK5xixtNlsyBzwIxoxE3IDlvwxZYVpo1tZY8RFeNZ,iv:5jIVtd0KDUDIPtMMWWPLYkr0wZZeDYZnJTqVtSEgd38=,tag:0ho7nKaVmzHmCQMpBfY6oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qkt8anezrv89yj8clxg5mhsgps8ygvsndjsn763p7t77eyx3uufs8turrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMnVaUkpud2s2ZTRSazZh
            Ylg3MXY4d3VON0FaUEZLL1Eza092UnFCbkNRClVTQjJnRGNHck5Rd29zT3I1T3Vu
            RTc5eEhBQ3R4Ymp6bS9yZDYvWWtvbUEKLS0tIDUxRUdPVW5va3RkYmo4YlZwcy9O
            QTNadHYyWHd3dlFlU25YVVFiL0RvemcKsy4yL/FcRGcXV+ZbgwTpGlfuX00KheIU
            Ii0X6vgCdMRQBz0RzbtJKO+NKrHH3Oi3tZ8xXsoHSpX+w5mwyw9SCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T02:33:45Z"
    mac: ENC[AES256_GCM,data:FY9uQgYMJERW8Ow4NrN+EVzEUS68WyyQjU/1lDVUtn4VBIaZrqftodiFXwQpV2mvCkWDNrEQ5dIHuKLGpFfo4ceRLqVgsHcAiOxz0hC5O6/09uWizlvRCfUfc7CTjgz8h99wfxES5AaIz9LM0//jhsEIUkNQ+2t1ocO8xl8Yg3g=,iv:1EX6MMC0yzWWoED2daJTsMUVK4Ys18asfx28zfehQ6k=,tag:oYcRH4oh701DHj/VMSlpuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
