apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:17+JqFK9TyOJIijvTWKZsLRljPRkpewcEt+bxlxJ1G4=,iv:xOxiBawZPbRBGea+9GF2jPCt5hldfXAkz43D4ESg+Tw=,tag:+y9MaFF8GuPiCxNF3bNeaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSFQ4aFJWN2VnWWdSbVd4
            TWpvUnBhc09RY3FjY1JjTGM0RlZtWjFDaEhvCm0wUFlkeWdEb3QyU3dDSVR5SkpX
            MlcvYW9JSTBhelpNaDlla25Wbjk4T1UKLS0tIHd0Tmc1VnZnc3IxS0RLN01kenJS
            a3d5U2xwV0NuNHMwTm1leFhxd2hsZlEK/fss/t5uz3D1+yrp1h9ndJYgKujwu/9J
            Wb2a/R74tDZr2Tt+uA2H60+nxTHMKYXHguaPSeFDfega4f6LBQgAXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T14:02:40Z"
    mac: ENC[AES256_GCM,data:0RfAz2DLAMjfj4JQiMkpONa9ZIAeiB2g1x1MQ6S4DOYY0zraJ6SY7csD4jTdg0VuxYEhfoqE8St934DlaAek+xFjTuNSEaYxr7Y9eb6bCEUdvuv+YYRmqrq/EcCJkGxxO6yVBVqe+32nq4E+nFbOdkRoE7mWi9faW2mQubhsMs8=,iv:6lEHOw1JDQ+gbiAc1Z05wOBwgDaEsrXR91r3hyNl3YI=,tag:btua4SJQobaZ0hihkBOxfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
