apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RNdb0zMAIWYgo5NQYyCQFZezrczpLIrrfKloo73jqWQ=,iv:27w+zGr53L1d9aQh74iHuXIJcKY3G/8c6zXt0xLg+18=,tag:i2eDNNONUGKYly/IG4vATA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0Y1YVd6MzR3bkcwVjk4
            dlVtYnZSbmc0WjVKQUlZQ3FaR0MyRytwM1FBCnlyeExoZDFYbytudGFjRVE5cEVh
            bk5RZklIZCt3K2FRRW9nZGxoWkhhbVUKLS0tIHJOSE00QXN4dk10bEpnZnNnNzgx
            QkNzSHNIWkVTMXZseUZ6V0RRbWJHV0UKzrfVc2ZykuKjS3VIpGSsKf++3eyekUtp
            WfnnwKb6tYAcYbxQOlAqV+NTvQ5e5ALBKg6u4WNoFnKkCUtzdjTRNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T13:13:58Z"
    mac: ENC[AES256_GCM,data:IDihPQ/P6+ZUsIIf/2YSan0Pz4ZtadNlNupPOMNn5KCduDqOjqd/9zsn5lG5ZowDJbqIgU8Ls21TnDYVP/SNGCVqbIfqBnhzQUS7+xMGnPcAn3y1uAFtpKJtxzkhUFX+yLf54KlTm02ZTQPXGoVglmghjNjPNjBWX54ytOEYock=,iv:znFen4EH6lRaflUv2l00k7YCyWGQLvStxe+ZP5tXvxs=,tag:9JYrnmfc3OZzjQbGfXGHYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
