apiVersion: v1
kind: Secret
metadata:
    name: postgresql-init
    namespace: database
type: Opaque
stringData:
    nextcloud.sql: ENC[AES256_GCM,data:KpmJ9+B0t0vWCaiXWWIK7AX3Ki1rSboRYrZJA27/ZUk5RsMucsOCQMUEyzZp1ezvs7urJGIPiq4re2sRSBYEC37aL4xVoXjenkYmL6RbiZIE+VoxjaUMa+xyb4TQ7crqtedERcOkCwkrwkDizgNeJFnqskXJ9nRaOEAWpbh0HOiV4fDOsJR7KnIC2jyJQMzhJw==,iv:WWym6gNXKQfN89AeBgtQ+FXHw/nD0mOtYw9zg4wUXZo=,tag:iJl+APcMs79jLLAoqgpPHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T10:26:34Z"
    mac: ENC[AES256_GCM,data:UidY7j0HziDBOns6gqEeOS13GnIgPRIOe0jaeT1WlpkqMhIV2Eds8BAQMUFn4ttrFzw4iHmSwG1e6uzZmnXUEApiCSIyVQRXno1S7PC9FK7L86oWVXadNtOMub+sxtBUW5P2awcbDQyv1opyE9r99w/zwFXyAO9JF9w5Viagx0s=,iv:nJOS2zPO12dePtje0TD8AmjpMo7tCBfH0hhC08jyQUQ=,tag:f++VnSf6Ma4I9LFXwKtodw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
