---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-sync-env
  namespace: default
data:
  GIT_SYNC_REPO: https://github.com/kilip/hass-config
  GIT_SYNC_BRANCH: main
  GIT_SYNC_ROOT: /tmp/hass-config/gitsync
  GIT_SYNC_DEST: latest
  GIT_SYNC_ADD_USER: "true"
  GIT_SYNC_HTTP_BIND: "0.0.0.0:8080"
  GIT_SYNC_HTTP_METRICS: "true"
  GIT_SYNC_EXECHOOK_COMMAND: "/post-sync.sh"
  GIT_SYNC_WAIT: "5"
  GIT_SYNC_MAX_SYNC_FAILURES: "-1"
  UID: "568"
  GID: "568"
