---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.5.3
    env:
      TZ: "${TIMEZONE}"
      INFLUXDB_HOST: influxdb.database.svc.cluster.local
      INFLUXDB_PORT: 8086
      INFLUXDB_SOURCE: "k8s"
      HASS_USING_GIT_CONFIG: "true"
    envFrom:
      - secretRef:
          name: home-assistant-secret
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_HASS_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: &hestia "hestia.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
              - *hestia
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 512Mi

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
      - name: vscode
        mountPath: /.vscode
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    persistence:
      secrets-mount:
        enabled: true
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        subPath:
          - path: GA_SERVICE_ACCOUNT
            mountPath: /config/ga-service-account.json
          - path: HOMELAB_SSH_PRIVATE_KEY
            mountPath: /config/.ssh/homelab
          - path: HOMELAB_SSH_PUBLIC_KEY
            mountPath: /config/.ssh/homelab.pub

    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        env:
          INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"
          INIT_POSTGRES_DBNAME: hass
          INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        envFrom:
          - secretRef:
              name: home-assistant-secret
