---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  - ./scripts.yaml
  - ./secrets.sops.yaml
  - ./helm-release.yaml
patchesStrategicMerge:
  - ./patches/vscode.yaml
