---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-scripts
  namespace: default
data:
  fake-config.sh: |
    #!/bin/sh -ex
    HASS_DIR="/tmp/hass-config/config"
    CONFIG_FILE="${HASS_DIR}/configuration.yaml"
    if [ ! -f "${CONFIG_FILE}" ]; then
        mkdir -p ${HASS_DIR}
        touch ${CONFIG_FILE}
        echo "default:" > ${CONFIG_FILE}
    fi


  post-sync.sh: |
    #!/bin/sh -ex
    mkdir -p /tmp/hass-config/config
    cp -avr /tmp/hass-config/latest/* /tmp/hass-config/config/
    exit 0
