---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-scripts
  namespace: default
data:
  post-sync.sh: |
    #!/bin/sh -ex
    mkdir -p /tmp/hass-config/config
    cp -av /tmp/hass-config/gitsync/latest/. /tmp/hass-config/config/
    exit 0
