apiVersion: v1
kind: ConfigMap
metadata:
  name: openhab
  namespace: default
data:
  post-sync.sh: |
    #!/bin/sh -ex
    mkdir -p /tmp/openhab/config
    cp -avr /tmp/openhab/latest/config/* /tmp/openhab/config/

  40-openhabcloud.sh: |
    #!/bin/bash -ex

    if [ ! -z ${OHC_UUID} ]
    then
        mkdir -p "${OPENHAB_USERDATA}"
        echo ${OHC_UUID} > "${OPENHAB_USERDATA}/uuid"
    fi

    if [ ! -z ${OHC_SECRET} ]
    then
        mkdir -p "${OPENHAB_USERDATA}/openhabcloud"
        echo ${OHC_SECRET} > "${OPENHAB_USERDATA}/openhabcloud/secret"
    fi
