---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openhab
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      fullnameOverride: openhab
    image:
      repository: openhab/openhab
      tag: 3.4.4-alpine

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch

    envFrom:
      - secretRef:
          name: openhab

    persistence:
      ohc-script:
        enabled: true
        type: configMap
        name: openhab
        defaultMode: 0777
        subPath:
          - path: 40-openhabcloud.sh
            mountPath: /etc/cont-init.d/40-openhabcloud.sh

      post-sync:
        enabled: true
        type: configMap
        name: openhab
        defaultMode: 0777

      openhab-config:
        enabled: true
        mountPath: /openhab/conf
        subPath: config
        accessMode: ReadWriteMany
        size: 1Gi
        storageClassName: longhorn

      openhab-userdata:
        enabled: true
        mountPath: /openhab/userdata
        subPath: userdata
        accessMode: ReadWriteMany
        size: 1Gi
        storageClassName: longhorn

    initContainers:
      01-sync-init:
        image: registry.k8s.io/git-sync/git-sync:v3.6.5
        envFrom:
          - secretRef:
              name: openhab
        args:
          - "-depth=1"
          - "--one-time=true"
          - "-v=3"
          - "--exechook-command=/bin/post-sync.sh"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
          - name: openhab-config
            mountPath: /tmp/openhab
          - name: post-sync
            subPath: post-sync.sh
            mountPath: /bin/post-sync.sh

    sidecars:
      01-sync-config:
        image: registry.k8s.io/git-sync/git-sync:v3.6.5
        args:
          - "-depth=1"
          - "--one-time=false"
          - "--wait=30"
          - "-v=3"
          - "--exechook-command=/bin/post-sync.sh"
        envFrom:
          - secretRef:
              name: openhab
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
          - name: openhab-config
            mountPath: /tmp/openhab
          - name: post-sync
            subPath: post-sync.sh
            mountPath: /bin/post-sync.sh

    controller:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:openhab
          hajimari.io/group: Home
        hosts:
          - host: &host "oh.itstoni.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    service:
      main:
        ports:
          http:
            port: 8080

    probes:
      liveness:
        enabled: false
        type: HTTP
        #enabled: false
      readiness:
        enabled: false
        type: HTTP
      startup:
        enabled: false
        type: HTTP

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1024Mi
