apiVersion: v1
kind: Secret
metadata:
    name: openhab
    namespace: default
type: Opaque
stringData:
    GIT_SYNC_REPO: ENC[AES256_GCM,data:6wyF9hxy+qC6s66CMfZfLMYV1GHrZulFx55VsA9WQnI=,iv:eTlYSUa+IDjjOB2Lss1MDGzFPg51OyqPq+yHzkhchcQ=,tag:X7VUicxq80ShxaCnWbXeGw==,type:str]
    GIT_SYNC_BRANCH: ENC[AES256_GCM,data:2QmwWQ==,iv:GbBW20JeX6zqzvH2QMepW4uINHjMhWfffQNIKj3e8Dc=,tag:SvK2+hy80oQ+E+RsXS0Hcg==,type:str]
    GIT_SYNC_ROOT: ENC[AES256_GCM,data:gjlABDfhi+xzc9vJ,iv:dkbh//kpZJUfrHNE03n/SugPDrkhcIsb3x26DG4t5Cw=,tag:BcsjPbdXB1sfABfJ4KhBCg==,type:str]
    GIT_SYNC_DEST: ENC[AES256_GCM,data:2UUK9yZI,iv:0Tqvu0cz/kZ3aQP8vofvCvDsECMd9wyC1XJ39AIOohE=,tag:7c3S940XcFSfX5MkqSXNJw==,type:str]
    GIT_SYNC_ADD_USER: ENC[AES256_GCM,data:nSV0/g==,iv:UCTJ2TKgaMX8kMfV60UjG63fWWsLO/LDjFUyT12fDRA=,tag:EP9vLgSieaQauVSrXE2yvw==,type:str]
    GIT_SYNC_USERNAME: ENC[AES256_GCM,data:KoFfXZ0=,iv:Qf/3OVKZgV49sNqOhniI0EkO1yLiaV6AcKpqtnhnVqc=,tag:5ki8agtuZP0+GHNkU8/qQA==,type:str]
    GIT_SYNC_PASSWORD: ENC[AES256_GCM,data:bf1wk4oIm+DotCWAB6Mb69yWoRqLkeES320ptxDME2AfdwyXhomWjg==,iv:J5i0Ysn8Bx4h0wUmBBMZ3mlk4InRTZ6m2QjmJzRFetg=,tag:Sfa1skvCYJI9CjJP40Qg0Q==,type:str]
    OHC_UUID: ENC[AES256_GCM,data:6Gb3Vj8cPj8UpdCQqO1+4cuFfcQtZEShHoKp3v7rTFpVdbr6,iv:qLqvOSC9o75tjt0kwn8/+PFS0tYRoMkzKQJjEwCY338=,tag:5LwPL0IKusu1sQ5jEyQ1rg==,type:str]
    OHC_SECRET: ENC[AES256_GCM,data:bXYH9tL9UAyjZJzB1/n7DxhuCxE=,iv:H3G9xd5WXwIqbd8jezib7Oz+QpHhU4xDC+aUtsxj4yM=,tag:5vFWbOESiAZ62tmBK5XJ+Q==,type:str]
    TZ: ENC[AES256_GCM,data:NRxOykvZ1oqPk/47vg==,iv:lU9607U8Z2tjKYQ8JuJLCcYGjKO96hw5f006YPHWu50=,tag:hC31BH1k9LTHkrP4Chj1/w==,type:str]
    USER_ID: ENC[AES256_GCM,data:IIJjbg==,iv:vTrG86ysoBwGkIs8FfaZpCBWQX5prt2GcJnegtZgFrc=,tag:JRXOFsSHc0RoWBQY0F3YDw==,type:str]
    GROUP_ID: ENC[AES256_GCM,data:R79vOA==,iv:mq8sVubpN9ShzpuF/BXhN6GFMg8OiJWzdSz9Sl600fs=,tag:YQ1okG0vrUzLVCQqI4ks3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-09T04:16:56Z"
    mac: ENC[AES256_GCM,data:9yY4zKG16jhSvcwhbmjwXxexoxpMoLEpmr9g5wKWg3EovRVQ497vwbQbwbNzoIvii73MP+hYRGqdjNiRKa57mhGRstBx4vW4S38fUkZr9I699HxZfkxGWnWnlxePZgOfXc/8uULT62h2QqX5dCmxoSeWS8cMXaL8SZqvKmB22S4=,iv:ctWHSi1AsCyGKawnR1rbD7P9ZDMxr/VEmOctLAN+9DM=,tag:6RtyRlSEMwUmNYyMRu5qdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
