apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iClCn/hToehR8qOeCIXNEneNPF7aOEKu,iv:RcJq+PJte4p7i/y7FsZsfHDXYo7XfbR6HW8Pi/6GmnQ=,tag:oWpAR9Wa1FuQDBEZ8BYdIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qkt8anezrv89yj8clxg5mhsgps8ygvsndjsn763p7t77eyx3uufs8turrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY2RLTGtKWWV3amVnYytX
            cnp2UFNBUmxvQm9JZEtDUTJOTjlpNFpCZmdnCnFXQzFJVnRjUDd0WUdTZFRaMC8z
            VVdmSDhhbXg3Z3k0UWcvTmtpdDBrYzQKLS0tIHlzZzZhaDIzeEpTK1Fsa0xaVmMw
            RExnYVhLYUVlNU1BOXV6VHorZlovZEkKKj3CLYAlkXCyokjryXo0n5UM7Vc19P2n
            BfG/dlGwHvM+np74Uq5NaqsXxcze8pbMIg9Pb/s/gfW9cj9YHm90+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T02:22:14Z"
    mac: ENC[AES256_GCM,data:+al0N7F/otQwlKVt1Cnhs7BowSfqtXriCLt69BrHiFO1/cIfMk0jUypQ0ki4D61SWViT1xeKckK8GXRAmtmM5u7Ga7td2JmGQ6ggk2DmPVmZhGjlAKFKpYd2bLCSTtlqAF4F9axcCgn+mbZS87Tfh0goWIECQHH3TA9NwGFjA3k=,iv:E7fUqJ7vfSyMIGvvvvQluOiOEOhtndQI1RaL8ISaeGk=,tag:wQ8xuJ5+iDascXhRFyTGHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
