---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: "{{ .dns_api_token }}"
  refreshInterval: 15m
  data:
    - secretKey: dns_api_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 557728c2-eb5c-4a84-80c3-b1bf00697525
        property: dns_api_token
