apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9cEZcXbovtyEQCfRHoPyE5WFo4shKoVVgL+SQ1RFYMWczVxkg2cuMA==,iv:sHJe3F6BAJdgmQAHAs79nmN486bKmorABmoP6lNUvZI=,tag:aLNco6rc25SPNnUbEN2j1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ2RuZXhxS0IvYlIrMWFa
            d09OZFU2dVdoVU5JVVdBOHZSbDZ2MThaU0NFCnlESXY3RVpINVFwV25EWDZIVmVx
            UGcxL1lYSEpjRWlWdkJSbi9jeFVqTncKLS0tIGR6MXlHaVVSQkFPZUlhZjM4YWpn
            MUtJeTV1UXdhbW9peWNTNVlrK3c3bTQK69ZSPnMYQGjtP2hcmFhRJ9iGRhPcXMO5
            zVN3ZcjBQOW0Gvbp8jSxuGq4ft0JO/hzEiqHm6lZeuzrFudN2GbNnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T14:02:39Z"
    mac: ENC[AES256_GCM,data:aM8nR+KeeP/dDpohx7DyYAqz4ua3JYZuV4hjlPzi+Ifvoacbya51BgKNOjSsz/4xBEjJBGAwO5+ir4Ovnq7lqHV/eVQKDoi8TKVB+L/0CwMXbYBSSGvAEOXxHGFwb7XcWchfCQkHhA0k2i3jSFI8foiBwbcymk3xBUjsOzrjb0E=,iv:2umOJk3pBtoTbuKoMgnfhKSoNtgK4O3sNEVHBGaf010=,tag:HUOHFtcBUCvmYLUthgsp4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
