apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:or4uRENWyph6g2100JoON0JQ7fmY9lZOtPpjpzpxTkIGR2kN5vY8ew==,iv:T7cgbQLFISpiVovnqrmJF3KcXERisO77envZuImfe+w=,tag:dKHz97DTyLRWNnEwHTaUXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMnI2QkEwWkpneEJSSUd4
            dUdRTTJzNDZQUG5YbzNLeWVWSGVoZTFsYlJBClJnR2VtUURUeFhWQWVjakNPMFA2
            MTlmVmppd25mQlZsb3FxelFoVWthdjgKLS0tIDlzK2FobVNqRzd1T013Nk1lak9D
            aFRHQk11M3JrOUFETjVwVDZrU2JmK2cKHhfN9c9s9zCZlN5FIxgw99Or0ESmZG1q
            O6isUjMGCEDNb4jkHhEKuKL19seV1WufOWPqQS8sB4n5WCy9jgPdDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T13:13:58Z"
    mac: ENC[AES256_GCM,data:BMyuz8B7duEbYn46ezdjHA7xOoBOn/g5iSnY6JqtJc5Zd8TQFzFCcBqi0E0OIBCtgzjrMNkJxLxkIDGlToBohWuFVIu+6t4IGNuu3jApUY8Lq1MKrANFp88p4s4kdcVVP4Lw0DigugkZSh3MGFm59nK2tk6TTNsejtOOpPqy6kE=,iv:TZDDX3AMsRD73XWmWVoQWEJ2lubFITe3Lztfx6hxrzE=,tag:zH3T7KjYQA7+L86oqr1xMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
