kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_user: ENC[AES256_GCM,data:tW5hjg==,iv:tDNV7N/RBf3QIJ3/Qo9z19jVxRfQF68tqsBaROYNc1k=,tag:Ea9hPE6+xcfXJ6ZC6OaL2Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U4Q2eKsfT7vRBpM9,iv:0nhsMdQRP73aYuvIug+csVGoK93r4F3EjfW3JZq+0DM=,tag:FBJD1ncvxXklWBDQOLfV0Q==,type:str]
install_packages:
    - ENC[AES256_GCM,data:fmii7tNcBe04rby6OMxg,iv:lP2hZH1D+gb0pxlm5SNoK1r9bCs+YhbNAwVwH39Lgew=,tag:KSOLyDM40f2UHC426Fu3Lg==,type:str]
    - ENC[AES256_GCM,data:etYt5A==,iv:M7HkcM43Ebmm+9nxORk2j8bkdso71slBsUUu/6X0H2k=,tag:b7U/TlGTnfLnHiZJo3jkMw==,type:str]
    - ENC[AES256_GCM,data:vLqP,iv:8dROy78sTABrh0pz+GxbYHc7T7EhdgqHZrHU8Mq7NHU=,tag:MrCBo8eR3o3S48mgFbkbsw==,type:str]
kubevip_address: ENC[AES256_GCM,data:A0KXPGfXRcBmaQ==,iv:0opO98f8C9MBuqi7UA4ZcxLC6vvzUyOaVQpThghUy/w=,tag:3KzyDauusprjl0MPv2D1tw==,type:str]
certbot_domain: ENC[AES256_GCM,data:d98wwBPqOwKx3iw=,iv:maStE+deF8IBxufW6TfDa8fyeJh6drVwU0sTUXwrPhQ=,tag:/i06960MtB2QliR2obIqSw==,type:str]
certbot_cloudflare_email: ENC[AES256_GCM,data:1yFlA3OgErIixwxp/HI=,iv:6MOMHntupJMtRNnYOcJ93Q16sTDcdrDXTpgCggE7IVU=,tag:UrUCr1Ym9wJEh6DV0hd/pA==,type:str]
certbot_cloudflare_api_key: ENC[AES256_GCM,data:7ik4Gp3ptcmGyaK07NulwvPrxg+OMdCE1aAB48jgkJf5UqFe9Q==,iv:3Ysu/B5Nh57cFtJmGquH/a2kscoG7j3ouks3aw/BTDk=,tag:MiKDnX7/P/VGcsFQ6UCZzQ==,type:str]
homelab_user: ENC[AES256_GCM,data:vNkZC0mC/Q==,iv:zZmQwOqC7RTt0oYd34507cJiZnNcuDW9D7Y1o8Gm6Wo=,tag:QX143jFJfkFNjggNn5mRCg==,type:str]
password: ENC[AES256_GCM,data:dtTmjoFPF/XOdHBvhlk=,iv:kM8YRysh/jDu0P2QgpX/Q6b1TOk6SMlTEV5LjOo0b9I=,tag:ziQOFDRmhD9ICCtwOYoWvw==,type:str]
ssh_private_key: ENC[AES256_GCM,data:yWvbQlCdv0IrJeI7IeEJbNNOK5hxiNuxzQv0zaIKZUErwGrRtBeC+t6Ci8OAbx/Zq/Edn3XcoDAtKGWOlLZMaDPYRauxmMX7ba8I4ci7esSnhY9JGLEjq+NEOqG25vKmRb2MBqHcQH7sIrXau4UvDbc0vJI9dVAPpsNW5dwP6waAS4fqce9tijhdx+XW86SABDbdAY1GMEhawR3cj/Q4vaJSzhE+JNIAzt80SBO+Xg9D0cQyYmPBjAsQCVgg461qw/3yZEtvTZpf1tiK3BTYuLD8ly0k6kxtCHg8jkGDa23HsclR4ZoIEUJ5I6iRt+SI0qRB3C2DFXU64t7JX6Tf9GybpjgxvzkHs4gX4qc4E7gThx2wwo4yhfZEqNZtkV7fQWOBx22eLaatSOk7HlT9c88GTIuPCIoQ4gHjDl7+E3qqidG8MMX1E0BJ8ERbJ3CqeiWkYqwsqpMVlo1ZbPblQpaNZf9x50oAqEW8crqyYjZwD/eiaxsr6CXNy+y9dMAEA5WR/dE/nslOzaXgklBcqfKTW4cauhOEZcx0,iv:aeA5e6T6Ok3vO/6WwLjyjJC//qrOhu53xKR3tR833VA=,tag:93K9PoM67N7CWlqOZN5XHg==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:5ev/ao2XOS4ZcwieTH2NtKkDJxFIKUSMOzX0J+Zk43H6EZ/88zgVKlOnoh/seINY6pk6YJr/gWIgt5XPBB6dHimzMR02Yl1ug3dls2zJi+6FMs7cwz3wX9G2pXPn+Ml6,iv:5fY40DqvTjZCTEp2BAOP13ufTowiODCU0gr4O29UBEU=,tag:VthLPhhAYCv4cRofPdV9DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T12:14:20Z"
    mac: ENC[AES256_GCM,data:rb4IDdAI/QgCV34xtqMY/BOoWwajUpZPd58Umo6PRhVSyqZxlRJhbicEWRVQMQRHFeXVgUAd7Ee5wAiso142igFgoHADSGctxeJ/GnMxpVOhd3Br81ehnPvJADH+n4H5Q/GRHl9dTBiLm1NzDEKq21ArsfFZunaGmg5uwf/wR7Y=,iv:CzveQvlRrYzXATeRzOldIhdOkZtCwg7HfqI3E/V5itQ=,tag:ByZBnMDqCMbI+3g1ZW7O/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
