kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_user: ENC[AES256_GCM,data:tW5hjg==,iv:tDNV7N/RBf3QIJ3/Qo9z19jVxRfQF68tqsBaROYNc1k=,tag:Ea9hPE6+xcfXJ6ZC6OaL2Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U4Q2eKsfT7vRBpM9,iv:0nhsMdQRP73aYuvIug+csVGoK93r4F3EjfW3JZq+0DM=,tag:FBJD1ncvxXklWBDQOLfV0Q==,type:str]
install_packages:
    - ENC[AES256_GCM,data:fmii7tNcBe04rby6OMxg,iv:lP2hZH1D+gb0pxlm5SNoK1r9bCs+YhbNAwVwH39Lgew=,tag:KSOLyDM40f2UHC426Fu3Lg==,type:str]
    - ENC[AES256_GCM,data:etYt5A==,iv:M7HkcM43Ebmm+9nxORk2j8bkdso71slBsUUu/6X0H2k=,tag:b7U/TlGTnfLnHiZJo3jkMw==,type:str]
    - ENC[AES256_GCM,data:vLqP,iv:8dROy78sTABrh0pz+GxbYHc7T7EhdgqHZrHU8Mq7NHU=,tag:MrCBo8eR3o3S48mgFbkbsw==,type:str]
kubevip_address: ENC[AES256_GCM,data:A0KXPGfXRcBmaQ==,iv:0opO98f8C9MBuqi7UA4ZcxLC6vvzUyOaVQpThghUy/w=,tag:3KzyDauusprjl0MPv2D1tw==,type:str]
certbot_domain: ENC[AES256_GCM,data:d98wwBPqOwKx3iw=,iv:maStE+deF8IBxufW6TfDa8fyeJh6drVwU0sTUXwrPhQ=,tag:/i06960MtB2QliR2obIqSw==,type:str]
certbot_cloudflare_email: ENC[AES256_GCM,data:1yFlA3OgErIixwxp/HI=,iv:6MOMHntupJMtRNnYOcJ93Q16sTDcdrDXTpgCggE7IVU=,tag:UrUCr1Ym9wJEh6DV0hd/pA==,type:str]
certbot_cloudflare_api_key: ENC[AES256_GCM,data:7ik4Gp3ptcmGyaK07NulwvPrxg+OMdCE1aAB48jgkJf5UqFe9Q==,iv:3Ysu/B5Nh57cFtJmGquH/a2kscoG7j3ouks3aw/BTDk=,tag:MiKDnX7/P/VGcsFQ6UCZzQ==,type:str]
homelab_user: ENC[AES256_GCM,data:vNkZC0mC/Q==,iv:zZmQwOqC7RTt0oYd34507cJiZnNcuDW9D7Y1o8Gm6Wo=,tag:QX143jFJfkFNjggNn5mRCg==,type:str]
homelab_user_password: ENC[AES256_GCM,data:w4VEgSLkOFExo5VYKJWDeGzerMZcN7/LjUYADXVNwrPXf+YFMHEEimJZndOM7tSnsDhOUMFgwCTfg/JFmYAQ7dUQmfFWcydDrRfQlWWy5AfcP088UV2mOAaAfPvb2/0rIVYfT3Y=,iv:KwfcFZgb7rFBmqENIV/7amOzhQOs7W6JiHSLbzBfAB4=,tag:evpIcOf2dXP2cGtjFshAGQ==,type:str]
homelab_user_ssh_private_key: ENC[AES256_GCM,data:1jYs0wVXtEUgAwiqaAp7SLLmFwivnsMV0yCJQO1FNSSct0lQdaILckcqDVmD8nGP/Hw5l8GYXbGPKHq61CutMW5JXzc32Wiv1eV0MNxb9Ey4GCoD24DGpsnm13ddkGEnL/TdHqR39nOBkIM0NjlIXOcTxNVAEO7JR3DxZWYCwbGOcDNqFrLF/TjbtVGyqvt+JiwtncSutr6KGciRi74qXFLbAW8Z/fs1Fpq9rBWXi4D/O/hkJCr7bOmLDCiYHC6kBHqug0pHVIm1Ix9WiA+8SIR1zw5BI4SrcfEPA+gClp58W4//VQ01trEK1b3dNuC2hqTcSJEk/geN24TirICMYYvuI9xxShwMkUrfSo5o3C1F1Gsbsdrgt0H6Fe1c7PYhelg7BU3XzCUnFphTk5WTpAqhX9tWX5pJA3v4f42JR7aMRpmp+9u1A33OkHM2NOEwcVgOPfuX3kfYVBDTwS60V6PRdkxAR+q+MiOrdNW97lP3rsXv4jjgKh/y/uYixJsY2edEZVlqMVS500LoWylVPR4c+A0c6fKB6K5k,iv:g8WyalosQab3Da1P0gXOkqn3knjeaoq+3mRZwbk7oHM=,tag:O87DAxM9YPzFcXNVNHJxNQ==,type:str]
homelab_user_ssh_public_key: ENC[AES256_GCM,data:fA6x8hqM9rizK/z6GNHqUMX24kaeaucY8TaJ7UPBhuwKKtrIKFFBYNdMeHCmd8d83SDSRxMDiqbiO7qxrAiSdJ7W+6J2Fqw541Lc4lFMAQIzUmy/j3a9c1k/4QUU+D8R,iv:tWU4bXjktDQkUlwm43wioHd8jYP7OnX/gGGaO9Crejs=,tag:G2s8vYmBA9pFUPPjslWn1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T12:34:48Z"
    mac: ENC[AES256_GCM,data:X7LX9wUeQlk0RDf1fHPU6hGR0iFT4R+bMYSO/DSIQO65V4oWcmJG8HCOXIaJ3HCsbGdC0fl0imIVX4zwVHsjPlYfJBOm67cPLURhNUYJFKkmHfIu7cH9PnCiXQYzQ3UfezBqk49D9cQyk/FMJPucEha87yNF1RCcNZ2jGU1iydE=,iv:iIjh6UD0+WTie20ABo69fbCBsaXhrPnFJtqJraeRyNg=,tag:sskRdCv5v/diImn7uqG2ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
