tunnel: ENC[AES256_GCM,data:MJegeA==,iv:cW2yFoqAayZzQD1e90qpCjEglRec3+iToHmQwrgOkhI=,tag:79TW8e89b82NB/LHdZ7cSQ==,type:bool]
tunnel_credentials_json: ENC[AES256_GCM,data:doMQCZTqjK1d++UPIbyHoWsVsdF+650/YYzyZUQsC2ThrpilYCxsmfSgPq2acqtwe4Wy5CXQkzx4O6D1eu9jZNcTKkWgJVRcu2zv0iTv5h1LbHhGe/QeKfpme+BFv9TG6lshhjVZoV1yLor3JGuPPsUBb+W8So+ntz8e0sZDJ1NuB/UNealBivJIeaK/RfDOPa5bnL+4r6ERabMT748kvHJqaxnBvINalJA7KNpy,iv:igOMFWKPpl6tFv8l1qoohkSgElks0IztsBSCIEhgZNo=,tag:71HncM1rwBgtvW5LZrgmuQ==,type:str]
tunnel_env: {}
tunnel_id: ENC[AES256_GCM,data:e4+24fgBIk/KKiOWnmyoldofK2WNTdgkYxgjaDZZMMKZVwC6,iv:UkkoMbkcxKxzeXeOQschQf9zKNrPF/17t3GvHqzaM88=,tag:LqeWP+hFdvhUzSa3SAV/vQ==,type:str]
tunnel_ingress_rules:
    - hostname: ENC[AES256_GCM,data:KEHviMCcruG+SxnQpyf/VJW5,iv:sL6iP513vASTZOzO0Ngb3nXgoqgi/AAIcXrcChBndCg=,tag:1xlp4s/s1JAp3y9oaXUZmg==,type:str]
      service: ENC[AES256_GCM,data:sQBciU0EJXNG1rY4qMN/Qg==,iv:a+al7Y+cQ3obXodgeL0igTqPpkbYBC0hB2GRxjkpdxA=,tag:SayAu7Tzj6qHKYXzvSKBAw==,type:str]
    - hostname: ENC[AES256_GCM,data:wfmyjvGvHhcvXJv5lwo=,iv:JcxzzPpJtuBsoIMHCG3nXB8ZhQEDTXNlAafsjx51oqg=,tag:bkqm4MoVSb56M+zBovNzBg==,type:str]
      service: ENC[AES256_GCM,data:M+jqd0lOLoEtTs22JdLDo6wfI70y,iv:rAqI412wZuBS5lSeLb2f9UGNpcXOYd4XO6tj8Bx4hYs=,tag:tX9YCzAWYVRmxZig9lhgsw==,type:str]
    - hostname: ENC[AES256_GCM,data:5q0VlAJzOcoRMbhFC2Y=,iv:kN+14zelaUrG7uCtrWcHJyMbadcFz91CClr2Myef0nk=,tag:EWvfS3T7rJH5BChTmoSMSQ==,type:str]
      service: ENC[AES256_GCM,data:x3EEX/WVsE8UC5pqFeGVth5x+g==,iv:/kJeUXwgnlGD004PrF2McC0MvOaP/II8z6+VucqauL0=,tag:TEHOcO/Twn02EmldUl1MnQ==,type:str]
    - hostname: ENC[AES256_GCM,data:Po9GzIJ1QMXWHEgs9n4=,iv:uLjg1A8xDfUyrPsjYnKHFa8547kAUS4hvWgU2lVX/4s=,tag:6hnEI4vHuOwRDikzdlpdnQ==,type:str]
      service: ENC[AES256_GCM,data:mQarpVczagueoWtPjQAnRgni7Omq4iuWsJsoMw==,iv:FxyTCPSG20sy7ZaBnbaeFGITK1KcCJ5WArX3v/sE9G0=,tag:sxYNPcAgfizYTpzTrRMsIw==,type:str]
    - hostname: ENC[AES256_GCM,data:vE32JPH9/KBPzS5IcfQ=,iv:K6Pm88bNVKMuhjnipmUpURfXsW7w+Ca2pk3kzz7ZJF0=,tag:IDGsbRsemzlWVw0jfXXpKw==,type:str]
      service: ENC[AES256_GCM,data:fru+BfpTx27dK2mhR/jfpcOLsJM=,iv:yiN5SCJ1ot9qQO5r8O0zrJ+qxb75nQdylI86AHY5jcE=,tag:sAKJQUVqASrEnjfK7nz1Qw==,type:str]
    - hostname: ENC[AES256_GCM,data:hqiEG3yhAXnimnaEF7N9KA==,iv:fbyhGMiGk8sqO4lL4jJYHHCi8piE2dis5rbomcBeCjk=,tag:hPd4ZW2UCpSEq3jscerPUA==,type:str]
      service: ENC[AES256_GCM,data:h8Nh7tywApd1/CF7/TpLC6hq,iv:mC8h6Bwbx2PUhcZsnpjKi3Hs/W89h+4YWZWxUkbb5to=,tag:TGyytvkm9RgohYLMnEN6lQ==,type:str]
    - hostname: ENC[AES256_GCM,data:naiE/eKbrAF2qaL1jaal9g==,iv:3NAY44mOpvsYvdKOPc/D2gHUI0gM0QY6lFBgqPcPZjI=,tag:kTYncKyTZ9asmyPTN1Jdww==,type:str]
      service: ENC[AES256_GCM,data:cMXWNogxpQFdaTgw4lnI6v4Oo5JP,iv:LU6IqXSxKWIDwP/1uap7H4g+ShZ19wZnQczvdFVzTfA=,tag:iRVtQiD6Hp/8ASitty9gaQ==,type:str]
    - service: ENC[AES256_GCM,data:7V/Y0wtWO34uFSMIdeF3,iv:Azf2VciLNCsMQs7pacrNJwIHeaThoRIPlMlNduuNmQM=,tag:Nq5wRT1C+mI3PXTGqbBqwQ==,type:str]
tunnel_manage_locally: ENC[AES256_GCM,data:rbHACQ==,iv:RQ2ZyFOoyheBgw+/0OcSYplVuBX9ZH5oIGwpEJl29Dg=,tag:jV+IRaYF/mOJzPwDB8vIaQ==,type:bool]
sops:
    age:
        - recipient: age1fjy59ujj3j4e5l37wzsntvl288m06qyj97nujyklefw67eg5r9usuj4qxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETS9WQ1dONjd0bXFGdUtG
            OE02TmFTMExpOGZERW1TcWFNY3ZSMExxeHpnCjR0UVlNMzJZckxINnBGVmdXQm1j
            alZqd1poaURNT0x3R0hYRWN0ZVJHYzAKLS0tICtwS1JoSWN3RmtoazdDcVo2STlx
            S2VwMnpoRlRUSUJYV0ZKS0RSMlpHdFUKqZYSkvTmeJTls90yhDg0H7q2xRGjH3y7
            FqP4LJkxQRGWrMHMlfaV2wq5DQOE3bWcWhV0FKvocftcslyzMnliyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T07:41:00Z"
    mac: ENC[AES256_GCM,data:83WkdzApQDueRK2ucg2Zomx1RY28GArWjuMv/stB6nIAI6hWHU7+pHlLKYx5HEUOI6nDui4bLIdzOIAh0Xc/3eJXxWEupXlUA3lwkay/KsVYBLMKfzTorIidd7ZW+/m/4uDfRT+pNCOCi2xxDwr2W/CchnviKii5Lth9OFtvQwg=,iv:EkGl5mLzsX+b3khtFhtVyteWvqJvtpvN7/UtW74sKwE=,tag:bad/uxdn5aIVxazH8Ct/hQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
